// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic/user.proto

package com.xhpolaris.idlgen.basic;

/**
 * <pre>
 * 客户端透传
 * </pre>
 *
 * Protobuf type {@code basic.Extra}
 */
public final class Extra extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:basic.Extra)
    ExtraOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Extra.newBuilder() to construct.
  private Extra(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Extra() {
    clientIP_ = "";
    language_ = "";
    resolution_ = "";
    devicePlatform_ = "";
    deviceBrand_ = "";
    deviceId_ = "";
    operateSystem_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Extra();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.basic.UserProto.internal_static_basic_Extra_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.basic.UserProto.internal_static_basic_Extra_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.basic.Extra.class, com.xhpolaris.idlgen.basic.Extra.Builder.class);
  }

  public static final int CLIENTIP_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientIP_;
  /**
   * <code>string clientIP = 1;</code>
   * @return The clientIP.
   */
  @java.lang.Override
  public java.lang.String getClientIP() {
    java.lang.Object ref = clientIP_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientIP_ = s;
      return s;
    }
  }
  /**
   * <code>string clientIP = 1;</code>
   * @return The bytes for clientIP.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIPBytes() {
    java.lang.Object ref = clientIP_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientIP_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object language_;
  /**
   * <code>string language = 2;</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <code>string language = 2;</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESOLUTION_FIELD_NUMBER = 3;
  private volatile java.lang.Object resolution_;
  /**
   * <pre>
   * 像素比
   * </pre>
   *
   * <code>string resolution = 3;</code>
   * @return The resolution.
   */
  @java.lang.Override
  public java.lang.String getResolution() {
    java.lang.Object ref = resolution_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resolution_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 像素比
   * </pre>
   *
   * <code>string resolution = 3;</code>
   * @return The bytes for resolution.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResolutionBytes() {
    java.lang.Object ref = resolution_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resolution_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEPLATFORM_FIELD_NUMBER = 4;
  private volatile java.lang.Object devicePlatform_;
  /**
   * <pre>
   * 设备平台
   * </pre>
   *
   * <code>string devicePlatform = 4;</code>
   * @return The devicePlatform.
   */
  @java.lang.Override
  public java.lang.String getDevicePlatform() {
    java.lang.Object ref = devicePlatform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      devicePlatform_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备平台
   * </pre>
   *
   * <code>string devicePlatform = 4;</code>
   * @return The bytes for devicePlatform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDevicePlatformBytes() {
    java.lang.Object ref = devicePlatform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      devicePlatform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEBRAND_FIELD_NUMBER = 5;
  private volatile java.lang.Object deviceBrand_;
  /**
   * <pre>
   * 设备品牌
   * </pre>
   *
   * <code>string deviceBrand = 5;</code>
   * @return The deviceBrand.
   */
  @java.lang.Override
  public java.lang.String getDeviceBrand() {
    java.lang.Object ref = deviceBrand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceBrand_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备品牌
   * </pre>
   *
   * <code>string deviceBrand = 5;</code>
   * @return The bytes for deviceBrand.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceBrandBytes() {
    java.lang.Object ref = deviceBrand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceBrand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICEID_FIELD_NUMBER = 6;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>string deviceId = 6;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceId = 6;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATESYSTEM_FIELD_NUMBER = 7;
  private volatile java.lang.Object operateSystem_;
  /**
   * <code>string operateSystem = 7;</code>
   * @return The operateSystem.
   */
  @java.lang.Override
  public java.lang.String getOperateSystem() {
    java.lang.Object ref = operateSystem_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      operateSystem_ = s;
      return s;
    }
  }
  /**
   * <code>string operateSystem = 7;</code>
   * @return The bytes for operateSystem.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOperateSystemBytes() {
    java.lang.Object ref = operateSystem_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      operateSystem_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIP_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientIP_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, language_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resolution_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resolution_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(devicePlatform_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, devicePlatform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceBrand_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, deviceBrand_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operateSystem_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, operateSystem_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientIP_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientIP_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, language_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(resolution_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resolution_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(devicePlatform_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, devicePlatform_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceBrand_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, deviceBrand_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, deviceId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operateSystem_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, operateSystem_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.basic.Extra)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.basic.Extra other = (com.xhpolaris.idlgen.basic.Extra) obj;

    if (!getClientIP()
        .equals(other.getClientIP())) return false;
    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (!getResolution()
        .equals(other.getResolution())) return false;
    if (!getDevicePlatform()
        .equals(other.getDevicePlatform())) return false;
    if (!getDeviceBrand()
        .equals(other.getDeviceBrand())) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (!getOperateSystem()
        .equals(other.getOperateSystem())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
    hash = (53 * hash) + getClientIP().hashCode();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    hash = (37 * hash) + RESOLUTION_FIELD_NUMBER;
    hash = (53 * hash) + getResolution().hashCode();
    hash = (37 * hash) + DEVICEPLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getDevicePlatform().hashCode();
    hash = (37 * hash) + DEVICEBRAND_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceBrand().hashCode();
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + OPERATESYSTEM_FIELD_NUMBER;
    hash = (53 * hash) + getOperateSystem().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.basic.Extra parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.basic.Extra prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 客户端透传
   * </pre>
   *
   * Protobuf type {@code basic.Extra}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:basic.Extra)
      com.xhpolaris.idlgen.basic.ExtraOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.basic.UserProto.internal_static_basic_Extra_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.basic.UserProto.internal_static_basic_Extra_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.basic.Extra.class, com.xhpolaris.idlgen.basic.Extra.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.basic.Extra.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientIP_ = "";

      language_ = "";

      resolution_ = "";

      devicePlatform_ = "";

      deviceBrand_ = "";

      deviceId_ = "";

      operateSystem_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.basic.UserProto.internal_static_basic_Extra_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.basic.Extra getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.basic.Extra.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.basic.Extra build() {
      com.xhpolaris.idlgen.basic.Extra result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.basic.Extra buildPartial() {
      com.xhpolaris.idlgen.basic.Extra result = new com.xhpolaris.idlgen.basic.Extra(this);
      result.clientIP_ = clientIP_;
      result.language_ = language_;
      result.resolution_ = resolution_;
      result.devicePlatform_ = devicePlatform_;
      result.deviceBrand_ = deviceBrand_;
      result.deviceId_ = deviceId_;
      result.operateSystem_ = operateSystem_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.basic.Extra) {
        return mergeFrom((com.xhpolaris.idlgen.basic.Extra)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.basic.Extra other) {
      if (other == com.xhpolaris.idlgen.basic.Extra.getDefaultInstance()) return this;
      if (!other.getClientIP().isEmpty()) {
        clientIP_ = other.clientIP_;
        onChanged();
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        onChanged();
      }
      if (!other.getResolution().isEmpty()) {
        resolution_ = other.resolution_;
        onChanged();
      }
      if (!other.getDevicePlatform().isEmpty()) {
        devicePlatform_ = other.devicePlatform_;
        onChanged();
      }
      if (!other.getDeviceBrand().isEmpty()) {
        deviceBrand_ = other.deviceBrand_;
        onChanged();
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      if (!other.getOperateSystem().isEmpty()) {
        operateSystem_ = other.operateSystem_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              clientIP_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              language_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              resolution_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              devicePlatform_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              deviceBrand_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              deviceId_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              operateSystem_ = input.readStringRequireUtf8();

              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object clientIP_ = "";
    /**
     * <code>string clientIP = 1;</code>
     * @return The clientIP.
     */
    public java.lang.String getClientIP() {
      java.lang.Object ref = clientIP_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIP_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string clientIP = 1;</code>
     * @return The bytes for clientIP.
     */
    public com.google.protobuf.ByteString
        getClientIPBytes() {
      java.lang.Object ref = clientIP_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string clientIP = 1;</code>
     * @param value The clientIP to set.
     * @return This builder for chaining.
     */
    public Builder setClientIP(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientIP_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string clientIP = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientIP() {
      
      clientIP_ = getDefaultInstance().getClientIP();
      onChanged();
      return this;
    }
    /**
     * <code>string clientIP = 1;</code>
     * @param value The bytes for clientIP to set.
     * @return This builder for chaining.
     */
    public Builder setClientIPBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientIP_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <code>string language = 2;</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string language = 2;</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      language_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string language = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      
      language_ = getDefaultInstance().getLanguage();
      onChanged();
      return this;
    }
    /**
     * <code>string language = 2;</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      language_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object resolution_ = "";
    /**
     * <pre>
     * 像素比
     * </pre>
     *
     * <code>string resolution = 3;</code>
     * @return The resolution.
     */
    public java.lang.String getResolution() {
      java.lang.Object ref = resolution_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resolution_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 像素比
     * </pre>
     *
     * <code>string resolution = 3;</code>
     * @return The bytes for resolution.
     */
    public com.google.protobuf.ByteString
        getResolutionBytes() {
      java.lang.Object ref = resolution_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resolution_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 像素比
     * </pre>
     *
     * <code>string resolution = 3;</code>
     * @param value The resolution to set.
     * @return This builder for chaining.
     */
    public Builder setResolution(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resolution_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 像素比
     * </pre>
     *
     * <code>string resolution = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearResolution() {
      
      resolution_ = getDefaultInstance().getResolution();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 像素比
     * </pre>
     *
     * <code>string resolution = 3;</code>
     * @param value The bytes for resolution to set.
     * @return This builder for chaining.
     */
    public Builder setResolutionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resolution_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object devicePlatform_ = "";
    /**
     * <pre>
     * 设备平台
     * </pre>
     *
     * <code>string devicePlatform = 4;</code>
     * @return The devicePlatform.
     */
    public java.lang.String getDevicePlatform() {
      java.lang.Object ref = devicePlatform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        devicePlatform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备平台
     * </pre>
     *
     * <code>string devicePlatform = 4;</code>
     * @return The bytes for devicePlatform.
     */
    public com.google.protobuf.ByteString
        getDevicePlatformBytes() {
      java.lang.Object ref = devicePlatform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devicePlatform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备平台
     * </pre>
     *
     * <code>string devicePlatform = 4;</code>
     * @param value The devicePlatform to set.
     * @return This builder for chaining.
     */
    public Builder setDevicePlatform(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      devicePlatform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备平台
     * </pre>
     *
     * <code>string devicePlatform = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDevicePlatform() {
      
      devicePlatform_ = getDefaultInstance().getDevicePlatform();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备平台
     * </pre>
     *
     * <code>string devicePlatform = 4;</code>
     * @param value The bytes for devicePlatform to set.
     * @return This builder for chaining.
     */
    public Builder setDevicePlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      devicePlatform_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceBrand_ = "";
    /**
     * <pre>
     * 设备品牌
     * </pre>
     *
     * <code>string deviceBrand = 5;</code>
     * @return The deviceBrand.
     */
    public java.lang.String getDeviceBrand() {
      java.lang.Object ref = deviceBrand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceBrand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备品牌
     * </pre>
     *
     * <code>string deviceBrand = 5;</code>
     * @return The bytes for deviceBrand.
     */
    public com.google.protobuf.ByteString
        getDeviceBrandBytes() {
      java.lang.Object ref = deviceBrand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceBrand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备品牌
     * </pre>
     *
     * <code>string deviceBrand = 5;</code>
     * @param value The deviceBrand to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceBrand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceBrand_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备品牌
     * </pre>
     *
     * <code>string deviceBrand = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceBrand() {
      
      deviceBrand_ = getDefaultInstance().getDeviceBrand();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备品牌
     * </pre>
     *
     * <code>string deviceBrand = 5;</code>
     * @param value The bytes for deviceBrand to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceBrand_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string deviceId = 6;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceId = 6;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceId = 6;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 6;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object operateSystem_ = "";
    /**
     * <code>string operateSystem = 7;</code>
     * @return The operateSystem.
     */
    public java.lang.String getOperateSystem() {
      java.lang.Object ref = operateSystem_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operateSystem_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string operateSystem = 7;</code>
     * @return The bytes for operateSystem.
     */
    public com.google.protobuf.ByteString
        getOperateSystemBytes() {
      java.lang.Object ref = operateSystem_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operateSystem_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string operateSystem = 7;</code>
     * @param value The operateSystem to set.
     * @return This builder for chaining.
     */
    public Builder setOperateSystem(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      operateSystem_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string operateSystem = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOperateSystem() {
      
      operateSystem_ = getDefaultInstance().getOperateSystem();
      onChanged();
      return this;
    }
    /**
     * <code>string operateSystem = 7;</code>
     * @param value The bytes for operateSystem to set.
     * @return This builder for chaining.
     */
    public Builder setOperateSystemBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      operateSystem_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:basic.Extra)
  }

  // @@protoc_insertion_point(class_scope:basic.Extra)
  private static final com.xhpolaris.idlgen.basic.Extra DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.basic.Extra();
  }

  public static com.xhpolaris.idlgen.basic.Extra getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Extra>
      PARSER = new com.google.protobuf.AbstractParser<Extra>() {
    @java.lang.Override
    public Extra parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Extra> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Extra> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.basic.Extra getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

