// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/common.proto

package com.xhpolaris.idlgen.meowchat.content;

/**
 * Protobuf type {@code meowchat.content.Cat}
 */
public final class Cat extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.content.Cat)
    CatOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Cat.newBuilder() to construct.
  private Cat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Cat() {
    id_ = "";
    age_ = "";
    communityId_ = "";
    color_ = "";
    details_ = "";
    name_ = "";
    sex_ = "";
    area_ = "";
    avatars_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Cat();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.content.CommonProto.internal_static_meowchat_content_Cat_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.content.CommonProto.internal_static_meowchat_content_Cat_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.content.Cat.class, com.xhpolaris.idlgen.meowchat.content.Cat.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEAT_FIELD_NUMBER = 2;
  private long createAt_;
  /**
   * <code>int64 createAt = 2;</code>
   * @return The createAt.
   */
  @java.lang.Override
  public long getCreateAt() {
    return createAt_;
  }

  public static final int AGE_FIELD_NUMBER = 3;
  private volatile java.lang.Object age_;
  /**
   * <code>string age = 3;</code>
   * @return The age.
   */
  @java.lang.Override
  public java.lang.String getAge() {
    java.lang.Object ref = age_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      age_ = s;
      return s;
    }
  }
  /**
   * <code>string age = 3;</code>
   * @return The bytes for age.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgeBytes() {
    java.lang.Object ref = age_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      age_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMUNITYID_FIELD_NUMBER = 4;
  private volatile java.lang.Object communityId_;
  /**
   * <code>string communityId = 4;</code>
   * @return The communityId.
   */
  @java.lang.Override
  public java.lang.String getCommunityId() {
    java.lang.Object ref = communityId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      communityId_ = s;
      return s;
    }
  }
  /**
   * <code>string communityId = 4;</code>
   * @return The bytes for communityId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommunityIdBytes() {
    java.lang.Object ref = communityId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      communityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLOR_FIELD_NUMBER = 5;
  private volatile java.lang.Object color_;
  /**
   * <code>string color = 5;</code>
   * @return The color.
   */
  @java.lang.Override
  public java.lang.String getColor() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      color_ = s;
      return s;
    }
  }
  /**
   * <code>string color = 5;</code>
   * @return The bytes for color.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColorBytes() {
    java.lang.Object ref = color_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      color_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DETAILS_FIELD_NUMBER = 6;
  private volatile java.lang.Object details_;
  /**
   * <code>string details = 6;</code>
   * @return The details.
   */
  @java.lang.Override
  public java.lang.String getDetails() {
    java.lang.Object ref = details_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      details_ = s;
      return s;
    }
  }
  /**
   * <code>string details = 6;</code>
   * @return The bytes for details.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDetailsBytes() {
    java.lang.Object ref = details_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      details_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 7;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 7;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int POPULARITY_FIELD_NUMBER = 8;
  private long popularity_;
  /**
   * <code>int64 popularity = 8;</code>
   * @return The popularity.
   */
  @java.lang.Override
  public long getPopularity() {
    return popularity_;
  }

  public static final int SEX_FIELD_NUMBER = 9;
  private volatile java.lang.Object sex_;
  /**
   * <code>string sex = 9;</code>
   * @return The sex.
   */
  @java.lang.Override
  public java.lang.String getSex() {
    java.lang.Object ref = sex_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sex_ = s;
      return s;
    }
  }
  /**
   * <code>string sex = 9;</code>
   * @return The bytes for sex.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSexBytes() {
    java.lang.Object ref = sex_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sex_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 10;
  private long status_;
  /**
   * <code>int64 status = 10;</code>
   * @return The status.
   */
  @java.lang.Override
  public long getStatus() {
    return status_;
  }

  public static final int AREA_FIELD_NUMBER = 11;
  private volatile java.lang.Object area_;
  /**
   * <code>string area = 11;</code>
   * @return The area.
   */
  @java.lang.Override
  public java.lang.String getArea() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      area_ = s;
      return s;
    }
  }
  /**
   * <code>string area = 11;</code>
   * @return The bytes for area.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAreaBytes() {
    java.lang.Object ref = area_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      area_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISSNIPPED_FIELD_NUMBER = 12;
  private boolean isSnipped_;
  /**
   * <code>bool isSnipped = 12;</code>
   * @return The isSnipped.
   */
  @java.lang.Override
  public boolean getIsSnipped() {
    return isSnipped_;
  }

  public static final int ISSTERILIZED_FIELD_NUMBER = 13;
  private boolean isSterilized_;
  /**
   * <code>bool isSterilized = 13;</code>
   * @return The isSterilized.
   */
  @java.lang.Override
  public boolean getIsSterilized() {
    return isSterilized_;
  }

  public static final int AVATARS_FIELD_NUMBER = 14;
  private com.google.protobuf.LazyStringList avatars_;
  /**
   * <code>repeated string avatars = 14;</code>
   * @return A list containing the avatars.
   */
  public com.google.protobuf.ProtocolStringList
      getAvatarsList() {
    return avatars_;
  }
  /**
   * <code>repeated string avatars = 14;</code>
   * @return The count of avatars.
   */
  public int getAvatarsCount() {
    return avatars_.size();
  }
  /**
   * <code>repeated string avatars = 14;</code>
   * @param index The index of the element to return.
   * @return The avatars at the given index.
   */
  public java.lang.String getAvatars(int index) {
    return avatars_.get(index);
  }
  /**
   * <code>repeated string avatars = 14;</code>
   * @param index The index of the value to return.
   * @return The bytes of the avatars at the given index.
   */
  public com.google.protobuf.ByteString
      getAvatarsBytes(int index) {
    return avatars_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (createAt_ != 0L) {
      output.writeInt64(2, createAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(age_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, age_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(communityId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, communityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(details_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, details_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, name_);
    }
    if (popularity_ != 0L) {
      output.writeInt64(8, popularity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sex_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sex_);
    }
    if (status_ != 0L) {
      output.writeInt64(10, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(area_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, area_);
    }
    if (isSnipped_ != false) {
      output.writeBool(12, isSnipped_);
    }
    if (isSterilized_ != false) {
      output.writeBool(13, isSterilized_);
    }
    for (int i = 0; i < avatars_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, avatars_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (createAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, createAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(age_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, age_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(communityId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, communityId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(color_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, color_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(details_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, details_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, name_);
    }
    if (popularity_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, popularity_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sex_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sex_);
    }
    if (status_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, status_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(area_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, area_);
    }
    if (isSnipped_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, isSnipped_);
    }
    if (isSterilized_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, isSterilized_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < avatars_.size(); i++) {
        dataSize += computeStringSizeNoTag(avatars_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAvatarsList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.content.Cat)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.content.Cat other = (com.xhpolaris.idlgen.meowchat.content.Cat) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (getCreateAt()
        != other.getCreateAt()) return false;
    if (!getAge()
        .equals(other.getAge())) return false;
    if (!getCommunityId()
        .equals(other.getCommunityId())) return false;
    if (!getColor()
        .equals(other.getColor())) return false;
    if (!getDetails()
        .equals(other.getDetails())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (getPopularity()
        != other.getPopularity()) return false;
    if (!getSex()
        .equals(other.getSex())) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (!getArea()
        .equals(other.getArea())) return false;
    if (getIsSnipped()
        != other.getIsSnipped()) return false;
    if (getIsSterilized()
        != other.getIsSterilized()) return false;
    if (!getAvatarsList()
        .equals(other.getAvatarsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateAt());
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge().hashCode();
    hash = (37 * hash) + COMMUNITYID_FIELD_NUMBER;
    hash = (53 * hash) + getCommunityId().hashCode();
    hash = (37 * hash) + COLOR_FIELD_NUMBER;
    hash = (53 * hash) + getColor().hashCode();
    hash = (37 * hash) + DETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getDetails().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + POPULARITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPopularity());
    hash = (37 * hash) + SEX_FIELD_NUMBER;
    hash = (53 * hash) + getSex().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStatus());
    hash = (37 * hash) + AREA_FIELD_NUMBER;
    hash = (53 * hash) + getArea().hashCode();
    hash = (37 * hash) + ISSNIPPED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSnipped());
    hash = (37 * hash) + ISSTERILIZED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSterilized());
    if (getAvatarsCount() > 0) {
      hash = (37 * hash) + AVATARS_FIELD_NUMBER;
      hash = (53 * hash) + getAvatarsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.Cat parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.content.Cat prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.content.Cat}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.content.Cat)
      com.xhpolaris.idlgen.meowchat.content.CatOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.content.CommonProto.internal_static_meowchat_content_Cat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.content.CommonProto.internal_static_meowchat_content_Cat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.content.Cat.class, com.xhpolaris.idlgen.meowchat.content.Cat.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.content.Cat.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = "";

      createAt_ = 0L;

      age_ = "";

      communityId_ = "";

      color_ = "";

      details_ = "";

      name_ = "";

      popularity_ = 0L;

      sex_ = "";

      status_ = 0L;

      area_ = "";

      isSnipped_ = false;

      isSterilized_ = false;

      avatars_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.content.CommonProto.internal_static_meowchat_content_Cat_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.Cat getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.content.Cat.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.Cat build() {
      com.xhpolaris.idlgen.meowchat.content.Cat result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.Cat buildPartial() {
      com.xhpolaris.idlgen.meowchat.content.Cat result = new com.xhpolaris.idlgen.meowchat.content.Cat(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.createAt_ = createAt_;
      result.age_ = age_;
      result.communityId_ = communityId_;
      result.color_ = color_;
      result.details_ = details_;
      result.name_ = name_;
      result.popularity_ = popularity_;
      result.sex_ = sex_;
      result.status_ = status_;
      result.area_ = area_;
      result.isSnipped_ = isSnipped_;
      result.isSterilized_ = isSterilized_;
      if (((bitField0_ & 0x00000001) != 0)) {
        avatars_ = avatars_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.avatars_ = avatars_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.content.Cat) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.content.Cat)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.content.Cat other) {
      if (other == com.xhpolaris.idlgen.meowchat.content.Cat.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.getCreateAt() != 0L) {
        setCreateAt(other.getCreateAt());
      }
      if (!other.getAge().isEmpty()) {
        age_ = other.age_;
        onChanged();
      }
      if (!other.getCommunityId().isEmpty()) {
        communityId_ = other.communityId_;
        onChanged();
      }
      if (!other.getColor().isEmpty()) {
        color_ = other.color_;
        onChanged();
      }
      if (!other.getDetails().isEmpty()) {
        details_ = other.details_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getPopularity() != 0L) {
        setPopularity(other.getPopularity());
      }
      if (!other.getSex().isEmpty()) {
        sex_ = other.sex_;
        onChanged();
      }
      if (other.getStatus() != 0L) {
        setStatus(other.getStatus());
      }
      if (!other.getArea().isEmpty()) {
        area_ = other.area_;
        onChanged();
      }
      if (other.getIsSnipped() != false) {
        setIsSnipped(other.getIsSnipped());
      }
      if (other.getIsSterilized() != false) {
        setIsSterilized(other.getIsSterilized());
      }
      if (!other.avatars_.isEmpty()) {
        if (avatars_.isEmpty()) {
          avatars_ = other.avatars_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAvatarsIsMutable();
          avatars_.addAll(other.avatars_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              createAt_ = input.readInt64();

              break;
            } // case 16
            case 26: {
              age_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              communityId_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              color_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              details_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              name_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 64: {
              popularity_ = input.readInt64();

              break;
            } // case 64
            case 74: {
              sex_ = input.readStringRequireUtf8();

              break;
            } // case 74
            case 80: {
              status_ = input.readInt64();

              break;
            } // case 80
            case 90: {
              area_ = input.readStringRequireUtf8();

              break;
            } // case 90
            case 96: {
              isSnipped_ = input.readBool();

              break;
            } // case 96
            case 104: {
              isSterilized_ = input.readBool();

              break;
            } // case 104
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureAvatarsIsMutable();
              avatars_.add(s);
              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private long createAt_ ;
    /**
     * <code>int64 createAt = 2;</code>
     * @return The createAt.
     */
    @java.lang.Override
    public long getCreateAt() {
      return createAt_;
    }
    /**
     * <code>int64 createAt = 2;</code>
     * @param value The createAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreateAt(long value) {
      
      createAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 createAt = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateAt() {
      
      createAt_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object age_ = "";
    /**
     * <code>string age = 3;</code>
     * @return The age.
     */
    public java.lang.String getAge() {
      java.lang.Object ref = age_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        age_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string age = 3;</code>
     * @return The bytes for age.
     */
    public com.google.protobuf.ByteString
        getAgeBytes() {
      java.lang.Object ref = age_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        age_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string age = 3;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string age = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      
      age_ = getDefaultInstance().getAge();
      onChanged();
      return this;
    }
    /**
     * <code>string age = 3;</code>
     * @param value The bytes for age to set.
     * @return This builder for chaining.
     */
    public Builder setAgeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      age_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object communityId_ = "";
    /**
     * <code>string communityId = 4;</code>
     * @return The communityId.
     */
    public java.lang.String getCommunityId() {
      java.lang.Object ref = communityId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        communityId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string communityId = 4;</code>
     * @return The bytes for communityId.
     */
    public com.google.protobuf.ByteString
        getCommunityIdBytes() {
      java.lang.Object ref = communityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        communityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string communityId = 4;</code>
     * @param value The communityId to set.
     * @return This builder for chaining.
     */
    public Builder setCommunityId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      communityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string communityId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommunityId() {
      
      communityId_ = getDefaultInstance().getCommunityId();
      onChanged();
      return this;
    }
    /**
     * <code>string communityId = 4;</code>
     * @param value The bytes for communityId to set.
     * @return This builder for chaining.
     */
    public Builder setCommunityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      communityId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object color_ = "";
    /**
     * <code>string color = 5;</code>
     * @return The color.
     */
    public java.lang.String getColor() {
      java.lang.Object ref = color_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        color_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string color = 5;</code>
     * @return The bytes for color.
     */
    public com.google.protobuf.ByteString
        getColorBytes() {
      java.lang.Object ref = color_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        color_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string color = 5;</code>
     * @param value The color to set.
     * @return This builder for chaining.
     */
    public Builder setColor(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      color_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string color = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearColor() {
      
      color_ = getDefaultInstance().getColor();
      onChanged();
      return this;
    }
    /**
     * <code>string color = 5;</code>
     * @param value The bytes for color to set.
     * @return This builder for chaining.
     */
    public Builder setColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      color_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object details_ = "";
    /**
     * <code>string details = 6;</code>
     * @return The details.
     */
    public java.lang.String getDetails() {
      java.lang.Object ref = details_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        details_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string details = 6;</code>
     * @return The bytes for details.
     */
    public com.google.protobuf.ByteString
        getDetailsBytes() {
      java.lang.Object ref = details_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        details_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string details = 6;</code>
     * @param value The details to set.
     * @return This builder for chaining.
     */
    public Builder setDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      details_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string details = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetails() {
      
      details_ = getDefaultInstance().getDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string details = 6;</code>
     * @param value The bytes for details to set.
     * @return This builder for chaining.
     */
    public Builder setDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      details_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 7;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 7;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 7;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 7;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private long popularity_ ;
    /**
     * <code>int64 popularity = 8;</code>
     * @return The popularity.
     */
    @java.lang.Override
    public long getPopularity() {
      return popularity_;
    }
    /**
     * <code>int64 popularity = 8;</code>
     * @param value The popularity to set.
     * @return This builder for chaining.
     */
    public Builder setPopularity(long value) {
      
      popularity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 popularity = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPopularity() {
      
      popularity_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object sex_ = "";
    /**
     * <code>string sex = 9;</code>
     * @return The sex.
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sex_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sex = 9;</code>
     * @return The bytes for sex.
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sex = 9;</code>
     * @param value The sex to set.
     * @return This builder for chaining.
     */
    public Builder setSex(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sex_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sex = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSex() {
      
      sex_ = getDefaultInstance().getSex();
      onChanged();
      return this;
    }
    /**
     * <code>string sex = 9;</code>
     * @param value The bytes for sex to set.
     * @return This builder for chaining.
     */
    public Builder setSexBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sex_ = value;
      onChanged();
      return this;
    }

    private long status_ ;
    /**
     * <code>int64 status = 10;</code>
     * @return The status.
     */
    @java.lang.Override
    public long getStatus() {
      return status_;
    }
    /**
     * <code>int64 status = 10;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(long value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 status = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object area_ = "";
    /**
     * <code>string area = 11;</code>
     * @return The area.
     */
    public java.lang.String getArea() {
      java.lang.Object ref = area_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        area_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string area = 11;</code>
     * @return The bytes for area.
     */
    public com.google.protobuf.ByteString
        getAreaBytes() {
      java.lang.Object ref = area_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        area_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string area = 11;</code>
     * @param value The area to set.
     * @return This builder for chaining.
     */
    public Builder setArea(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      area_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string area = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearArea() {
      
      area_ = getDefaultInstance().getArea();
      onChanged();
      return this;
    }
    /**
     * <code>string area = 11;</code>
     * @param value The bytes for area to set.
     * @return This builder for chaining.
     */
    public Builder setAreaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      area_ = value;
      onChanged();
      return this;
    }

    private boolean isSnipped_ ;
    /**
     * <code>bool isSnipped = 12;</code>
     * @return The isSnipped.
     */
    @java.lang.Override
    public boolean getIsSnipped() {
      return isSnipped_;
    }
    /**
     * <code>bool isSnipped = 12;</code>
     * @param value The isSnipped to set.
     * @return This builder for chaining.
     */
    public Builder setIsSnipped(boolean value) {
      
      isSnipped_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isSnipped = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSnipped() {
      
      isSnipped_ = false;
      onChanged();
      return this;
    }

    private boolean isSterilized_ ;
    /**
     * <code>bool isSterilized = 13;</code>
     * @return The isSterilized.
     */
    @java.lang.Override
    public boolean getIsSterilized() {
      return isSterilized_;
    }
    /**
     * <code>bool isSterilized = 13;</code>
     * @param value The isSterilized to set.
     * @return This builder for chaining.
     */
    public Builder setIsSterilized(boolean value) {
      
      isSterilized_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool isSterilized = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsSterilized() {
      
      isSterilized_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList avatars_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAvatarsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        avatars_ = new com.google.protobuf.LazyStringArrayList(avatars_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @return A list containing the avatars.
     */
    public com.google.protobuf.ProtocolStringList
        getAvatarsList() {
      return avatars_.getUnmodifiableView();
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @return The count of avatars.
     */
    public int getAvatarsCount() {
      return avatars_.size();
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @param index The index of the element to return.
     * @return The avatars at the given index.
     */
    public java.lang.String getAvatars(int index) {
      return avatars_.get(index);
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @param index The index of the value to return.
     * @return The bytes of the avatars at the given index.
     */
    public com.google.protobuf.ByteString
        getAvatarsBytes(int index) {
      return avatars_.getByteString(index);
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @param index The index to set the value at.
     * @param value The avatars to set.
     * @return This builder for chaining.
     */
    public Builder setAvatars(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAvatarsIsMutable();
      avatars_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @param value The avatars to add.
     * @return This builder for chaining.
     */
    public Builder addAvatars(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAvatarsIsMutable();
      avatars_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @param values The avatars to add.
     * @return This builder for chaining.
     */
    public Builder addAllAvatars(
        java.lang.Iterable<java.lang.String> values) {
      ensureAvatarsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, avatars_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatars() {
      avatars_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string avatars = 14;</code>
     * @param value The bytes of the avatars to add.
     * @return This builder for chaining.
     */
    public Builder addAvatarsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAvatarsIsMutable();
      avatars_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.content.Cat)
  }

  // @@protoc_insertion_point(class_scope:meowchat.content.Cat)
  private static final com.xhpolaris.idlgen.meowchat.content.Cat DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.content.Cat();
  }

  public static com.xhpolaris.idlgen.meowchat.content.Cat getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Cat>
      PARSER = new com.google.protobuf.AbstractParser<Cat>() {
    @java.lang.Override
    public Cat parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Cat> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Cat> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.content.Cat getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

