// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/content.proto

package com.xhpolaris.idlgen.meowchat.content;

public interface CreateImageRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.content.CreateImageResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string imageIds = 1;</code>
   * @return A list containing the imageIds.
   */
  java.util.List<java.lang.String>
      getImageIdsList();
  /**
   * <code>repeated string imageIds = 1;</code>
   * @return The count of imageIds.
   */
  int getImageIdsCount();
  /**
   * <code>repeated string imageIds = 1;</code>
   * @param index The index of the element to return.
   * @return The imageIds at the given index.
   */
  java.lang.String getImageIds(int index);
  /**
   * <code>repeated string imageIds = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the imageIds at the given index.
   */
  com.google.protobuf.ByteString
      getImageIdsBytes(int index);
}
