// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/content.proto

package com.xhpolaris.idlgen.meowchat.content;

public interface DeleteImageRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.content.DeleteImageResp)
    com.google.protobuf.MessageOrBuilder {
}
