// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/content.proto

package com.xhpolaris.idlgen.meowchat.content;

public interface DeletePlanReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.content.DeletePlanReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string planId = 1;</code>
   * @return The planId.
   */
  java.lang.String getPlanId();
  /**
   * <code>string planId = 1;</code>
   * @return The bytes for planId.
   */
  com.google.protobuf.ByteString
      getPlanIdBytes();
}
