// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/content.proto

package com.xhpolaris.idlgen.meowchat.content;

/**
 * Protobuf type {@code meowchat.content.ListCatResp}
 */
public final class ListCatResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.content.ListCatResp)
    ListCatRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListCatResp.newBuilder() to construct.
  private ListCatResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListCatResp() {
    cats_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListCatResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_ListCatResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_ListCatResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.content.ListCatResp.class, com.xhpolaris.idlgen.meowchat.content.ListCatResp.Builder.class);
  }

  public static final int CATS_FIELD_NUMBER = 1;
  private java.util.List<com.xhpolaris.idlgen.meowchat.content.Cat> cats_;
  /**
   * <code>repeated .meowchat.content.Cat cats = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.xhpolaris.idlgen.meowchat.content.Cat> getCatsList() {
    return cats_;
  }
  /**
   * <code>repeated .meowchat.content.Cat cats = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.xhpolaris.idlgen.meowchat.content.CatOrBuilder> 
      getCatsOrBuilderList() {
    return cats_;
  }
  /**
   * <code>repeated .meowchat.content.Cat cats = 1;</code>
   */
  @java.lang.Override
  public int getCatsCount() {
    return cats_.size();
  }
  /**
   * <code>repeated .meowchat.content.Cat cats = 1;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.content.Cat getCats(int index) {
    return cats_.get(index);
  }
  /**
   * <code>repeated .meowchat.content.Cat cats = 1;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.content.CatOrBuilder getCatsOrBuilder(
      int index) {
    return cats_.get(index);
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private long total_;
  /**
   * <code>int64 total = 2;</code>
   * @return The total.
   */
  @java.lang.Override
  public long getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < cats_.size(); i++) {
      output.writeMessage(1, cats_.get(i));
    }
    if (total_ != 0L) {
      output.writeInt64(2, total_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < cats_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, cats_.get(i));
    }
    if (total_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, total_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.content.ListCatResp)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.content.ListCatResp other = (com.xhpolaris.idlgen.meowchat.content.ListCatResp) obj;

    if (!getCatsList()
        .equals(other.getCatsList())) return false;
    if (getTotal()
        != other.getTotal()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCatsCount() > 0) {
      hash = (37 * hash) + CATS_FIELD_NUMBER;
      hash = (53 * hash) + getCatsList().hashCode();
    }
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotal());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.content.ListCatResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.content.ListCatResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.content.ListCatResp)
      com.xhpolaris.idlgen.meowchat.content.ListCatRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_ListCatResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_ListCatResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.content.ListCatResp.class, com.xhpolaris.idlgen.meowchat.content.ListCatResp.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.content.ListCatResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (catsBuilder_ == null) {
        cats_ = java.util.Collections.emptyList();
      } else {
        cats_ = null;
        catsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_ListCatResp_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.ListCatResp getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.content.ListCatResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.ListCatResp build() {
      com.xhpolaris.idlgen.meowchat.content.ListCatResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.ListCatResp buildPartial() {
      com.xhpolaris.idlgen.meowchat.content.ListCatResp result = new com.xhpolaris.idlgen.meowchat.content.ListCatResp(this);
      int from_bitField0_ = bitField0_;
      if (catsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          cats_ = java.util.Collections.unmodifiableList(cats_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.cats_ = cats_;
      } else {
        result.cats_ = catsBuilder_.build();
      }
      result.total_ = total_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.content.ListCatResp) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.content.ListCatResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.content.ListCatResp other) {
      if (other == com.xhpolaris.idlgen.meowchat.content.ListCatResp.getDefaultInstance()) return this;
      if (catsBuilder_ == null) {
        if (!other.cats_.isEmpty()) {
          if (cats_.isEmpty()) {
            cats_ = other.cats_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCatsIsMutable();
            cats_.addAll(other.cats_);
          }
          onChanged();
        }
      } else {
        if (!other.cats_.isEmpty()) {
          if (catsBuilder_.isEmpty()) {
            catsBuilder_.dispose();
            catsBuilder_ = null;
            cats_ = other.cats_;
            bitField0_ = (bitField0_ & ~0x00000001);
            catsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCatsFieldBuilder() : null;
          } else {
            catsBuilder_.addAllMessages(other.cats_);
          }
        }
      }
      if (other.getTotal() != 0L) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.xhpolaris.idlgen.meowchat.content.Cat m =
                  input.readMessage(
                      com.xhpolaris.idlgen.meowchat.content.Cat.parser(),
                      extensionRegistry);
              if (catsBuilder_ == null) {
                ensureCatsIsMutable();
                cats_.add(m);
              } else {
                catsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 16: {
              total_ = input.readInt64();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.xhpolaris.idlgen.meowchat.content.Cat> cats_ =
      java.util.Collections.emptyList();
    private void ensureCatsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        cats_ = new java.util.ArrayList<com.xhpolaris.idlgen.meowchat.content.Cat>(cats_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.content.Cat, com.xhpolaris.idlgen.meowchat.content.Cat.Builder, com.xhpolaris.idlgen.meowchat.content.CatOrBuilder> catsBuilder_;

    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public java.util.List<com.xhpolaris.idlgen.meowchat.content.Cat> getCatsList() {
      if (catsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(cats_);
      } else {
        return catsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public int getCatsCount() {
      if (catsBuilder_ == null) {
        return cats_.size();
      } else {
        return catsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.content.Cat getCats(int index) {
      if (catsBuilder_ == null) {
        return cats_.get(index);
      } else {
        return catsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder setCats(
        int index, com.xhpolaris.idlgen.meowchat.content.Cat value) {
      if (catsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCatsIsMutable();
        cats_.set(index, value);
        onChanged();
      } else {
        catsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder setCats(
        int index, com.xhpolaris.idlgen.meowchat.content.Cat.Builder builderForValue) {
      if (catsBuilder_ == null) {
        ensureCatsIsMutable();
        cats_.set(index, builderForValue.build());
        onChanged();
      } else {
        catsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder addCats(com.xhpolaris.idlgen.meowchat.content.Cat value) {
      if (catsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCatsIsMutable();
        cats_.add(value);
        onChanged();
      } else {
        catsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder addCats(
        int index, com.xhpolaris.idlgen.meowchat.content.Cat value) {
      if (catsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCatsIsMutable();
        cats_.add(index, value);
        onChanged();
      } else {
        catsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder addCats(
        com.xhpolaris.idlgen.meowchat.content.Cat.Builder builderForValue) {
      if (catsBuilder_ == null) {
        ensureCatsIsMutable();
        cats_.add(builderForValue.build());
        onChanged();
      } else {
        catsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder addCats(
        int index, com.xhpolaris.idlgen.meowchat.content.Cat.Builder builderForValue) {
      if (catsBuilder_ == null) {
        ensureCatsIsMutable();
        cats_.add(index, builderForValue.build());
        onChanged();
      } else {
        catsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder addAllCats(
        java.lang.Iterable<? extends com.xhpolaris.idlgen.meowchat.content.Cat> values) {
      if (catsBuilder_ == null) {
        ensureCatsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cats_);
        onChanged();
      } else {
        catsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder clearCats() {
      if (catsBuilder_ == null) {
        cats_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        catsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public Builder removeCats(int index) {
      if (catsBuilder_ == null) {
        ensureCatsIsMutable();
        cats_.remove(index);
        onChanged();
      } else {
        catsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.content.Cat.Builder getCatsBuilder(
        int index) {
      return getCatsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.content.CatOrBuilder getCatsOrBuilder(
        int index) {
      if (catsBuilder_ == null) {
        return cats_.get(index);  } else {
        return catsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public java.util.List<? extends com.xhpolaris.idlgen.meowchat.content.CatOrBuilder> 
         getCatsOrBuilderList() {
      if (catsBuilder_ != null) {
        return catsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(cats_);
      }
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.content.Cat.Builder addCatsBuilder() {
      return getCatsFieldBuilder().addBuilder(
          com.xhpolaris.idlgen.meowchat.content.Cat.getDefaultInstance());
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.content.Cat.Builder addCatsBuilder(
        int index) {
      return getCatsFieldBuilder().addBuilder(
          index, com.xhpolaris.idlgen.meowchat.content.Cat.getDefaultInstance());
    }
    /**
     * <code>repeated .meowchat.content.Cat cats = 1;</code>
     */
    public java.util.List<com.xhpolaris.idlgen.meowchat.content.Cat.Builder> 
         getCatsBuilderList() {
      return getCatsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.content.Cat, com.xhpolaris.idlgen.meowchat.content.Cat.Builder, com.xhpolaris.idlgen.meowchat.content.CatOrBuilder> 
        getCatsFieldBuilder() {
      if (catsBuilder_ == null) {
        catsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xhpolaris.idlgen.meowchat.content.Cat, com.xhpolaris.idlgen.meowchat.content.Cat.Builder, com.xhpolaris.idlgen.meowchat.content.CatOrBuilder>(
                cats_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        cats_ = null;
      }
      return catsBuilder_;
    }

    private long total_ ;
    /**
     * <code>int64 total = 2;</code>
     * @return The total.
     */
    @java.lang.Override
    public long getTotal() {
      return total_;
    }
    /**
     * <code>int64 total = 2;</code>
     * @param value The total to set.
     * @return This builder for chaining.
     */
    public Builder setTotal(long value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 total = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotal() {
      
      total_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.content.ListCatResp)
  }

  // @@protoc_insertion_point(class_scope:meowchat.content.ListCatResp)
  private static final com.xhpolaris.idlgen.meowchat.content.ListCatResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.content.ListCatResp();
  }

  public static com.xhpolaris.idlgen.meowchat.content.ListCatResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListCatResp>
      PARSER = new com.google.protobuf.AbstractParser<ListCatResp>() {
    @java.lang.Override
    public ListCatResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListCatResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListCatResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.content.ListCatResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

