// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/common.proto

package com.xhpolaris.idlgen.meowchat.content;

/**
 * Protobuf enum {@code meowchat.content.PlanType}
 */
public enum PlanType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TypeFeed = 0;</code>
   */
  TypeFeed(0),
  /**
   * <code>TypeCastrate = 1;</code>
   */
  TypeCastrate(1),
  /**
   * <code>TypeHeal = 2;</code>
   */
  TypeHeal(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TypeFeed = 0;</code>
   */
  public static final int TypeFeed_VALUE = 0;
  /**
   * <code>TypeCastrate = 1;</code>
   */
  public static final int TypeCastrate_VALUE = 1;
  /**
   * <code>TypeHeal = 2;</code>
   */
  public static final int TypeHeal_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static PlanType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static PlanType forNumber(int value) {
    switch (value) {
      case 0: return TypeFeed;
      case 1: return TypeCastrate;
      case 2: return TypeHeal;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<PlanType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      PlanType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<PlanType>() {
          public PlanType findValueByNumber(int number) {
            return PlanType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.content.CommonProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final PlanType[] VALUES = values();

  public static PlanType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private PlanType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:meowchat.content.PlanType)
}

