// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/content.proto

package com.xhpolaris.idlgen.meowchat.content;

/**
 * Protobuf type {@code meowchat.content.RetrieveUserFishResp}
 */
public final class RetrieveUserFishResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.content.RetrieveUserFishResp)
    RetrieveUserFishRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RetrieveUserFishResp.newBuilder() to construct.
  private RetrieveUserFishResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RetrieveUserFishResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RetrieveUserFishResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_RetrieveUserFishResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_RetrieveUserFishResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp.class, com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp.Builder.class);
  }

  public static final int FISH_FIELD_NUMBER = 1;
  private long fish_;
  /**
   * <code>int64 fish = 1;</code>
   * @return The fish.
   */
  @java.lang.Override
  public long getFish() {
    return fish_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fish_ != 0L) {
      output.writeInt64(1, fish_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fish_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, fish_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp other = (com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp) obj;

    if (getFish()
        != other.getFish()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FISH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFish());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.content.RetrieveUserFishResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.content.RetrieveUserFishResp)
      com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_RetrieveUserFishResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_RetrieveUserFishResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp.class, com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      fish_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.content.ContentProto.internal_static_meowchat_content_RetrieveUserFishResp_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp build() {
      com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp buildPartial() {
      com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp result = new com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp(this);
      result.fish_ = fish_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp other) {
      if (other == com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp.getDefaultInstance()) return this;
      if (other.getFish() != 0L) {
        setFish(other.getFish());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fish_ = input.readInt64();

              break;
            } // case 8
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long fish_ ;
    /**
     * <code>int64 fish = 1;</code>
     * @return The fish.
     */
    @java.lang.Override
    public long getFish() {
      return fish_;
    }
    /**
     * <code>int64 fish = 1;</code>
     * @param value The fish to set.
     * @return This builder for chaining.
     */
    public Builder setFish(long value) {
      
      fish_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 fish = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFish() {
      
      fish_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.content.RetrieveUserFishResp)
  }

  // @@protoc_insertion_point(class_scope:meowchat.content.RetrieveUserFishResp)
  private static final com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp();
  }

  public static com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetrieveUserFishResp>
      PARSER = new com.google.protobuf.AbstractParser<RetrieveUserFishResp>() {
    @java.lang.Override
    public RetrieveUserFishResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RetrieveUserFishResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetrieveUserFishResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.content.RetrieveUserFishResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

