// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/content/content.proto

package com.xhpolaris.idlgen.meowchat.content;

public interface UpdatePlanReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.content.UpdatePlanReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.meowchat.content.Plan plan = 1;</code>
   * @return Whether the plan field is set.
   */
  boolean hasPlan();
  /**
   * <code>.meowchat.content.Plan plan = 1;</code>
   * @return The plan.
   */
  com.xhpolaris.idlgen.meowchat.content.Plan getPlan();
  /**
   * <code>.meowchat.content.Plan plan = 1;</code>
   */
  com.xhpolaris.idlgen.meowchat.content.PlanOrBuilder getPlanOrBuilder();
}
