// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/system/common.proto

package com.xhpolaris.idlgen.meowchat.system;

public interface ApplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.system.Apply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string applyId = 1;</code>
   * @return The applyId.
   */
  java.lang.String getApplyId();
  /**
   * <code>string applyId = 1;</code>
   * @return The bytes for applyId.
   */
  com.google.protobuf.ByteString
      getApplyIdBytes();

  /**
   * <code>string applicantId = 2;</code>
   * @return The applicantId.
   */
  java.lang.String getApplicantId();
  /**
   * <code>string applicantId = 2;</code>
   * @return The bytes for applicantId.
   */
  com.google.protobuf.ByteString
      getApplicantIdBytes();

  /**
   * <code>string communityId = 4;</code>
   * @return The communityId.
   */
  java.lang.String getCommunityId();
  /**
   * <code>string communityId = 4;</code>
   * @return The bytes for communityId.
   */
  com.google.protobuf.ByteString
      getCommunityIdBytes();
}
