// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/system/system.proto

package com.xhpolaris.idlgen.meowchat.system;

public interface ListApplyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.system.ListApplyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string communityId = 1;</code>
   * @return The communityId.
   */
  java.lang.String getCommunityId();
  /**
   * <code>string communityId = 1;</code>
   * @return The bytes for communityId.
   */
  com.google.protobuf.ByteString
      getCommunityIdBytes();
}
