// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/system/system.proto

package com.xhpolaris.idlgen.meowchat.system;

/**
 * Protobuf type {@code meowchat.system.RetrieveAdminResp}
 */
public final class RetrieveAdminResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.system.RetrieveAdminResp)
    RetrieveAdminRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RetrieveAdminResp.newBuilder() to construct.
  private RetrieveAdminResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RetrieveAdminResp() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RetrieveAdminResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.system.SystemProto.internal_static_meowchat_system_RetrieveAdminResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.system.SystemProto.internal_static_meowchat_system_RetrieveAdminResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp.class, com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp.Builder.class);
  }

  public static final int ADMIN_FIELD_NUMBER = 1;
  private com.xhpolaris.idlgen.meowchat.system.Admin admin_;
  /**
   * <code>.meowchat.system.Admin admin = 1;</code>
   * @return Whether the admin field is set.
   */
  @java.lang.Override
  public boolean hasAdmin() {
    return admin_ != null;
  }
  /**
   * <code>.meowchat.system.Admin admin = 1;</code>
   * @return The admin.
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.system.Admin getAdmin() {
    return admin_ == null ? com.xhpolaris.idlgen.meowchat.system.Admin.getDefaultInstance() : admin_;
  }
  /**
   * <code>.meowchat.system.Admin admin = 1;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.system.AdminOrBuilder getAdminOrBuilder() {
    return getAdmin();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (admin_ != null) {
      output.writeMessage(1, getAdmin());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (admin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAdmin());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp other = (com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp) obj;

    if (hasAdmin() != other.hasAdmin()) return false;
    if (hasAdmin()) {
      if (!getAdmin()
          .equals(other.getAdmin())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAdmin()) {
      hash = (37 * hash) + ADMIN_FIELD_NUMBER;
      hash = (53 * hash) + getAdmin().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.system.RetrieveAdminResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.system.RetrieveAdminResp)
      com.xhpolaris.idlgen.meowchat.system.RetrieveAdminRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.system.SystemProto.internal_static_meowchat_system_RetrieveAdminResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.system.SystemProto.internal_static_meowchat_system_RetrieveAdminResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp.class, com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (adminBuilder_ == null) {
        admin_ = null;
      } else {
        admin_ = null;
        adminBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.system.SystemProto.internal_static_meowchat_system_RetrieveAdminResp_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp build() {
      com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp buildPartial() {
      com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp result = new com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp(this);
      if (adminBuilder_ == null) {
        result.admin_ = admin_;
      } else {
        result.admin_ = adminBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp other) {
      if (other == com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp.getDefaultInstance()) return this;
      if (other.hasAdmin()) {
        mergeAdmin(other.getAdmin());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getAdminFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private com.xhpolaris.idlgen.meowchat.system.Admin admin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.system.Admin, com.xhpolaris.idlgen.meowchat.system.Admin.Builder, com.xhpolaris.idlgen.meowchat.system.AdminOrBuilder> adminBuilder_;
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     * @return Whether the admin field is set.
     */
    public boolean hasAdmin() {
      return adminBuilder_ != null || admin_ != null;
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     * @return The admin.
     */
    public com.xhpolaris.idlgen.meowchat.system.Admin getAdmin() {
      if (adminBuilder_ == null) {
        return admin_ == null ? com.xhpolaris.idlgen.meowchat.system.Admin.getDefaultInstance() : admin_;
      } else {
        return adminBuilder_.getMessage();
      }
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     */
    public Builder setAdmin(com.xhpolaris.idlgen.meowchat.system.Admin value) {
      if (adminBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        admin_ = value;
        onChanged();
      } else {
        adminBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     */
    public Builder setAdmin(
        com.xhpolaris.idlgen.meowchat.system.Admin.Builder builderForValue) {
      if (adminBuilder_ == null) {
        admin_ = builderForValue.build();
        onChanged();
      } else {
        adminBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     */
    public Builder mergeAdmin(com.xhpolaris.idlgen.meowchat.system.Admin value) {
      if (adminBuilder_ == null) {
        if (admin_ != null) {
          admin_ =
            com.xhpolaris.idlgen.meowchat.system.Admin.newBuilder(admin_).mergeFrom(value).buildPartial();
        } else {
          admin_ = value;
        }
        onChanged();
      } else {
        adminBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     */
    public Builder clearAdmin() {
      if (adminBuilder_ == null) {
        admin_ = null;
        onChanged();
      } else {
        admin_ = null;
        adminBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.system.Admin.Builder getAdminBuilder() {
      
      onChanged();
      return getAdminFieldBuilder().getBuilder();
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.system.AdminOrBuilder getAdminOrBuilder() {
      if (adminBuilder_ != null) {
        return adminBuilder_.getMessageOrBuilder();
      } else {
        return admin_ == null ?
            com.xhpolaris.idlgen.meowchat.system.Admin.getDefaultInstance() : admin_;
      }
    }
    /**
     * <code>.meowchat.system.Admin admin = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.system.Admin, com.xhpolaris.idlgen.meowchat.system.Admin.Builder, com.xhpolaris.idlgen.meowchat.system.AdminOrBuilder> 
        getAdminFieldBuilder() {
      if (adminBuilder_ == null) {
        adminBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xhpolaris.idlgen.meowchat.system.Admin, com.xhpolaris.idlgen.meowchat.system.Admin.Builder, com.xhpolaris.idlgen.meowchat.system.AdminOrBuilder>(
                getAdmin(),
                getParentForChildren(),
                isClean());
        admin_ = null;
      }
      return adminBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.system.RetrieveAdminResp)
  }

  // @@protoc_insertion_point(class_scope:meowchat.system.RetrieveAdminResp)
  private static final com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp();
  }

  public static com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RetrieveAdminResp>
      PARSER = new com.google.protobuf.AbstractParser<RetrieveAdminResp>() {
    @java.lang.Override
    public RetrieveAdminResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RetrieveAdminResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RetrieveAdminResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.system.RetrieveAdminResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

