// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/system/system.proto

package com.xhpolaris.idlgen.meowchat.system;

public interface UpdateCommunityReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.system.UpdateCommunityReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string parentId = 3;</code>
   * @return The parentId.
   */
  java.lang.String getParentId();
  /**
   * <code>string parentId = 3;</code>
   * @return The bytes for parentId.
   */
  com.google.protobuf.ByteString
      getParentIdBytes();
}
