// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/comment/comment.proto

package com.xhpolaris.idlgen.platform.comment;

public interface DeleteCommentByIdRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.comment.DeleteCommentByIdResp)
    com.google.protobuf.MessageOrBuilder {
}
