// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/sts.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface ApplySignedUrlReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.ApplySignedUrlReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string prefix = 1;</code>
   * @return Whether the prefix field is set.
   */
  boolean hasPrefix();
  /**
   * <code>optional string prefix = 1;</code>
   * @return The prefix.
   */
  java.lang.String getPrefix();
  /**
   * <code>optional string prefix = 1;</code>
   * @return The bytes for prefix.
   */
  com.google.protobuf.ByteString
      getPrefixBytes();

  /**
   * <code>optional string suffix = 2;</code>
   * @return Whether the suffix field is set.
   */
  boolean hasSuffix();
  /**
   * <code>optional string suffix = 2;</code>
   * @return The suffix.
   */
  java.lang.String getSuffix();
  /**
   * <code>optional string suffix = 2;</code>
   * @return The bytes for suffix.
   */
  com.google.protobuf.ByteString
      getSuffixBytes();
}
