// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/collection.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface GetImageByCatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.GetImageByCatReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string catId = 1;</code>
   * @return The catId.
   */
  java.lang.String getCatId();
  /**
   * <code>string catId = 1;</code>
   * @return The bytes for catId.
   */
  com.google.protobuf.ByteString
      getCatIdBytes();

  /**
   * <code>optional string prevId = 2;</code>
   * @return Whether the prevId field is set.
   */
  boolean hasPrevId();
  /**
   * <code>optional string prevId = 2;</code>
   * @return The prevId.
   */
  java.lang.String getPrevId();
  /**
   * <code>optional string prevId = 2;</code>
   * @return The bytes for prevId.
   */
  com.google.protobuf.ByteString
      getPrevIdBytes();

  /**
   * <code>int64 limit = 3;</code>
   * @return The limit.
   */
  long getLimit();

  /**
   * <code>int64 offset = 4;</code>
   * @return The offset.
   */
  long getOffset();

  /**
   * <code>bool backward = 5;</code>
   * @return The backward.
   */
  boolean getBackward();
}
