// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/system.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

/**
 * Protobuf type {@code meowchat.core_api.GetNoticesResp}
 */
public final class GetNoticesResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.core_api.GetNoticesResp)
    GetNoticesRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetNoticesResp.newBuilder() to construct.
  private GetNoticesResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetNoticesResp() {
    notices_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetNoticesResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_GetNoticesResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_GetNoticesResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp.class, com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp.Builder.class);
  }

  public static final int NOTICES_FIELD_NUMBER = 1;
  private java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Notice> notices_;
  /**
   * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Notice> getNoticesList() {
    return notices_;
  }
  /**
   * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.xhpolaris.idlgen.meowchat.coreapi.NoticeOrBuilder> 
      getNoticesOrBuilderList() {
    return notices_;
  }
  /**
   * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
   */
  @java.lang.Override
  public int getNoticesCount() {
    return notices_.size();
  }
  /**
   * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.Notice getNotices(int index) {
    return notices_.get(index);
  }
  /**
   * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.NoticeOrBuilder getNoticesOrBuilder(
      int index) {
    return notices_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < notices_.size(); i++) {
      output.writeMessage(1, notices_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < notices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, notices_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp other = (com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp) obj;

    if (!getNoticesList()
        .equals(other.getNoticesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNoticesCount() > 0) {
      hash = (37 * hash) + NOTICES_FIELD_NUMBER;
      hash = (53 * hash) + getNoticesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.core_api.GetNoticesResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.core_api.GetNoticesResp)
      com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_GetNoticesResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_GetNoticesResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp.class, com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (noticesBuilder_ == null) {
        notices_ = java.util.Collections.emptyList();
      } else {
        notices_ = null;
        noticesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_GetNoticesResp_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp build() {
      com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp buildPartial() {
      com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp result = new com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp(this);
      int from_bitField0_ = bitField0_;
      if (noticesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          notices_ = java.util.Collections.unmodifiableList(notices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.notices_ = notices_;
      } else {
        result.notices_ = noticesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp other) {
      if (other == com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp.getDefaultInstance()) return this;
      if (noticesBuilder_ == null) {
        if (!other.notices_.isEmpty()) {
          if (notices_.isEmpty()) {
            notices_ = other.notices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNoticesIsMutable();
            notices_.addAll(other.notices_);
          }
          onChanged();
        }
      } else {
        if (!other.notices_.isEmpty()) {
          if (noticesBuilder_.isEmpty()) {
            noticesBuilder_.dispose();
            noticesBuilder_ = null;
            notices_ = other.notices_;
            bitField0_ = (bitField0_ & ~0x00000001);
            noticesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNoticesFieldBuilder() : null;
          } else {
            noticesBuilder_.addAllMessages(other.notices_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.xhpolaris.idlgen.meowchat.coreapi.Notice m =
                  input.readMessage(
                      com.xhpolaris.idlgen.meowchat.coreapi.Notice.parser(),
                      extensionRegistry);
              if (noticesBuilder_ == null) {
                ensureNoticesIsMutable();
                notices_.add(m);
              } else {
                noticesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Notice> notices_ =
      java.util.Collections.emptyList();
    private void ensureNoticesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        notices_ = new java.util.ArrayList<com.xhpolaris.idlgen.meowchat.coreapi.Notice>(notices_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.coreapi.Notice, com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder, com.xhpolaris.idlgen.meowchat.coreapi.NoticeOrBuilder> noticesBuilder_;

    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Notice> getNoticesList() {
      if (noticesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(notices_);
      } else {
        return noticesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public int getNoticesCount() {
      if (noticesBuilder_ == null) {
        return notices_.size();
      } else {
        return noticesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Notice getNotices(int index) {
      if (noticesBuilder_ == null) {
        return notices_.get(index);
      } else {
        return noticesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder setNotices(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Notice value) {
      if (noticesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNoticesIsMutable();
        notices_.set(index, value);
        onChanged();
      } else {
        noticesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder setNotices(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder builderForValue) {
      if (noticesBuilder_ == null) {
        ensureNoticesIsMutable();
        notices_.set(index, builderForValue.build());
        onChanged();
      } else {
        noticesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder addNotices(com.xhpolaris.idlgen.meowchat.coreapi.Notice value) {
      if (noticesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNoticesIsMutable();
        notices_.add(value);
        onChanged();
      } else {
        noticesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder addNotices(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Notice value) {
      if (noticesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNoticesIsMutable();
        notices_.add(index, value);
        onChanged();
      } else {
        noticesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder addNotices(
        com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder builderForValue) {
      if (noticesBuilder_ == null) {
        ensureNoticesIsMutable();
        notices_.add(builderForValue.build());
        onChanged();
      } else {
        noticesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder addNotices(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder builderForValue) {
      if (noticesBuilder_ == null) {
        ensureNoticesIsMutable();
        notices_.add(index, builderForValue.build());
        onChanged();
      } else {
        noticesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder addAllNotices(
        java.lang.Iterable<? extends com.xhpolaris.idlgen.meowchat.coreapi.Notice> values) {
      if (noticesBuilder_ == null) {
        ensureNoticesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, notices_);
        onChanged();
      } else {
        noticesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder clearNotices() {
      if (noticesBuilder_ == null) {
        notices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        noticesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public Builder removeNotices(int index) {
      if (noticesBuilder_ == null) {
        ensureNoticesIsMutable();
        notices_.remove(index);
        onChanged();
      } else {
        noticesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder getNoticesBuilder(
        int index) {
      return getNoticesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.NoticeOrBuilder getNoticesOrBuilder(
        int index) {
      if (noticesBuilder_ == null) {
        return notices_.get(index);  } else {
        return noticesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public java.util.List<? extends com.xhpolaris.idlgen.meowchat.coreapi.NoticeOrBuilder> 
         getNoticesOrBuilderList() {
      if (noticesBuilder_ != null) {
        return noticesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(notices_);
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder addNoticesBuilder() {
      return getNoticesFieldBuilder().addBuilder(
          com.xhpolaris.idlgen.meowchat.coreapi.Notice.getDefaultInstance());
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder addNoticesBuilder(
        int index) {
      return getNoticesFieldBuilder().addBuilder(
          index, com.xhpolaris.idlgen.meowchat.coreapi.Notice.getDefaultInstance());
    }
    /**
     * <code>repeated .meowchat.core_api.Notice notices = 1;</code>
     */
    public java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder> 
         getNoticesBuilderList() {
      return getNoticesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.coreapi.Notice, com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder, com.xhpolaris.idlgen.meowchat.coreapi.NoticeOrBuilder> 
        getNoticesFieldBuilder() {
      if (noticesBuilder_ == null) {
        noticesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xhpolaris.idlgen.meowchat.coreapi.Notice, com.xhpolaris.idlgen.meowchat.coreapi.Notice.Builder, com.xhpolaris.idlgen.meowchat.coreapi.NoticeOrBuilder>(
                notices_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        notices_ = null;
      }
      return noticesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.core_api.GetNoticesResp)
  }

  // @@protoc_insertion_point(class_scope:meowchat.core_api.GetNoticesResp)
  private static final com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp();
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetNoticesResp>
      PARSER = new com.google.protobuf.AbstractParser<GetNoticesResp>() {
    @java.lang.Override
    public GetNoticesResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetNoticesResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetNoticesResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.GetNoticesResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

