// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/plan.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface GetPlanDetailRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.GetPlanDetailResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.meowchat.core_api.Plan plan = 1;</code>
   * @return Whether the plan field is set.
   */
  boolean hasPlan();
  /**
   * <code>.meowchat.core_api.Plan plan = 1;</code>
   * @return The plan.
   */
  com.xhpolaris.idlgen.meowchat.coreapi.Plan getPlan();
  /**
   * <code>.meowchat.core_api.Plan plan = 1;</code>
   */
  com.xhpolaris.idlgen.meowchat.coreapi.PlanOrBuilder getPlanOrBuilder();
}
