// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/post.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface GetPostPreviewsReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.GetPostPreviewsReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.basic.PaginationOptions paginationOption = 1;</code>
   * @return Whether the paginationOption field is set.
   */
  boolean hasPaginationOption();
  /**
   * <code>.basic.PaginationOptions paginationOption = 1;</code>
   * @return The paginationOption.
   */
  com.xhpolaris.idlgen.basic.PaginationOptions getPaginationOption();
  /**
   * <code>.basic.PaginationOptions paginationOption = 1;</code>
   */
  com.xhpolaris.idlgen.basic.PaginationOptionsOrBuilder getPaginationOptionOrBuilder();

  /**
   * <code>optional bool onlyOfficial = 2;</code>
   * @return Whether the onlyOfficial field is set.
   */
  boolean hasOnlyOfficial();
  /**
   * <code>optional bool onlyOfficial = 2;</code>
   * @return The onlyOfficial.
   */
  boolean getOnlyOfficial();

  /**
   * <code>optional string onlyUserId = 3;</code>
   * @return Whether the onlyUserId field is set.
   */
  boolean hasOnlyUserId();
  /**
   * <code>optional string onlyUserId = 3;</code>
   * @return The onlyUserId.
   */
  java.lang.String getOnlyUserId();
  /**
   * <code>optional string onlyUserId = 3;</code>
   * @return The bytes for onlyUserId.
   */
  com.google.protobuf.ByteString
      getOnlyUserIdBytes();

  /**
   * <code>optional .meowchat.core_api.SearchOptions searchOptions = 4;</code>
   * @return Whether the searchOptions field is set.
   */
  boolean hasSearchOptions();
  /**
   * <code>optional .meowchat.core_api.SearchOptions searchOptions = 4;</code>
   * @return The searchOptions.
   */
  com.xhpolaris.idlgen.meowchat.coreapi.SearchOptions getSearchOptions();
  /**
   * <code>optional .meowchat.core_api.SearchOptions searchOptions = 4;</code>
   */
  com.xhpolaris.idlgen.meowchat.coreapi.SearchOptionsOrBuilder getSearchOptionsOrBuilder();
}
