// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/plan.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

/**
 * Protobuf type {@code meowchat.core_api.GetPlanPreviewsReq}
 */
public final class GetPlanPreviewsReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.core_api.GetPlanPreviewsReq)
    GetPlanPreviewsReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPlanPreviewsReq.newBuilder() to construct.
  private GetPlanPreviewsReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPlanPreviewsReq() {
    catId_ = "";
    onlyUserId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetPlanPreviewsReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.coreapi.PlanProto.internal_static_meowchat_core_api_GetPlanPreviewsReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.coreapi.PlanProto.internal_static_meowchat_core_api_GetPlanPreviewsReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq.class, com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq.Builder.class);
  }

  private int bitField0_;
  public static final int CATID_FIELD_NUMBER = 1;
  private volatile java.lang.Object catId_;
  /**
   * <code>optional string catId = 1;</code>
   * @return Whether the catId field is set.
   */
  @java.lang.Override
  public boolean hasCatId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string catId = 1;</code>
   * @return The catId.
   */
  @java.lang.Override
  public java.lang.String getCatId() {
    java.lang.Object ref = catId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      catId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string catId = 1;</code>
   * @return The bytes for catId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCatIdBytes() {
    java.lang.Object ref = catId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      catId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ONLYUSERID_FIELD_NUMBER = 2;
  private volatile java.lang.Object onlyUserId_;
  /**
   * <code>optional string onlyUserId = 2;</code>
   * @return Whether the onlyUserId field is set.
   */
  @java.lang.Override
  public boolean hasOnlyUserId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string onlyUserId = 2;</code>
   * @return The onlyUserId.
   */
  @java.lang.Override
  public java.lang.String getOnlyUserId() {
    java.lang.Object ref = onlyUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      onlyUserId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string onlyUserId = 2;</code>
   * @return The bytes for onlyUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOnlyUserIdBytes() {
    java.lang.Object ref = onlyUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      onlyUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGINATIONOPTION_FIELD_NUMBER = 3;
  private com.xhpolaris.idlgen.basic.PaginationOptions paginationOption_;
  /**
   * <code>.basic.PaginationOptions paginationOption = 3;</code>
   * @return Whether the paginationOption field is set.
   */
  @java.lang.Override
  public boolean hasPaginationOption() {
    return paginationOption_ != null;
  }
  /**
   * <code>.basic.PaginationOptions paginationOption = 3;</code>
   * @return The paginationOption.
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.basic.PaginationOptions getPaginationOption() {
    return paginationOption_ == null ? com.xhpolaris.idlgen.basic.PaginationOptions.getDefaultInstance() : paginationOption_;
  }
  /**
   * <code>.basic.PaginationOptions paginationOption = 3;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.basic.PaginationOptionsOrBuilder getPaginationOptionOrBuilder() {
    return getPaginationOption();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, catId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, onlyUserId_);
    }
    if (paginationOption_ != null) {
      output.writeMessage(3, getPaginationOption());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, catId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, onlyUserId_);
    }
    if (paginationOption_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPaginationOption());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq other = (com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq) obj;

    if (hasCatId() != other.hasCatId()) return false;
    if (hasCatId()) {
      if (!getCatId()
          .equals(other.getCatId())) return false;
    }
    if (hasOnlyUserId() != other.hasOnlyUserId()) return false;
    if (hasOnlyUserId()) {
      if (!getOnlyUserId()
          .equals(other.getOnlyUserId())) return false;
    }
    if (hasPaginationOption() != other.hasPaginationOption()) return false;
    if (hasPaginationOption()) {
      if (!getPaginationOption()
          .equals(other.getPaginationOption())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCatId()) {
      hash = (37 * hash) + CATID_FIELD_NUMBER;
      hash = (53 * hash) + getCatId().hashCode();
    }
    if (hasOnlyUserId()) {
      hash = (37 * hash) + ONLYUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getOnlyUserId().hashCode();
    }
    if (hasPaginationOption()) {
      hash = (37 * hash) + PAGINATIONOPTION_FIELD_NUMBER;
      hash = (53 * hash) + getPaginationOption().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.core_api.GetPlanPreviewsReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.core_api.GetPlanPreviewsReq)
      com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.coreapi.PlanProto.internal_static_meowchat_core_api_GetPlanPreviewsReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.coreapi.PlanProto.internal_static_meowchat_core_api_GetPlanPreviewsReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq.class, com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      catId_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      onlyUserId_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      if (paginationOptionBuilder_ == null) {
        paginationOption_ = null;
      } else {
        paginationOption_ = null;
        paginationOptionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.PlanProto.internal_static_meowchat_core_api_GetPlanPreviewsReq_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq build() {
      com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq buildPartial() {
      com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq result = new com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.catId_ = catId_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.onlyUserId_ = onlyUserId_;
      if (paginationOptionBuilder_ == null) {
        result.paginationOption_ = paginationOption_;
      } else {
        result.paginationOption_ = paginationOptionBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq other) {
      if (other == com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq.getDefaultInstance()) return this;
      if (other.hasCatId()) {
        bitField0_ |= 0x00000001;
        catId_ = other.catId_;
        onChanged();
      }
      if (other.hasOnlyUserId()) {
        bitField0_ |= 0x00000002;
        onlyUserId_ = other.onlyUserId_;
        onChanged();
      }
      if (other.hasPaginationOption()) {
        mergePaginationOption(other.getPaginationOption());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              catId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              onlyUserId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getPaginationOptionFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object catId_ = "";
    /**
     * <code>optional string catId = 1;</code>
     * @return Whether the catId field is set.
     */
    public boolean hasCatId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string catId = 1;</code>
     * @return The catId.
     */
    public java.lang.String getCatId() {
      java.lang.Object ref = catId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        catId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string catId = 1;</code>
     * @return The bytes for catId.
     */
    public com.google.protobuf.ByteString
        getCatIdBytes() {
      java.lang.Object ref = catId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        catId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string catId = 1;</code>
     * @param value The catId to set.
     * @return This builder for chaining.
     */
    public Builder setCatId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      catId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string catId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCatId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      catId_ = getDefaultInstance().getCatId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string catId = 1;</code>
     * @param value The bytes for catId to set.
     * @return This builder for chaining.
     */
    public Builder setCatIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      catId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object onlyUserId_ = "";
    /**
     * <code>optional string onlyUserId = 2;</code>
     * @return Whether the onlyUserId field is set.
     */
    public boolean hasOnlyUserId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string onlyUserId = 2;</code>
     * @return The onlyUserId.
     */
    public java.lang.String getOnlyUserId() {
      java.lang.Object ref = onlyUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        onlyUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string onlyUserId = 2;</code>
     * @return The bytes for onlyUserId.
     */
    public com.google.protobuf.ByteString
        getOnlyUserIdBytes() {
      java.lang.Object ref = onlyUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        onlyUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string onlyUserId = 2;</code>
     * @param value The onlyUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOnlyUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      onlyUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string onlyUserId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOnlyUserId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      onlyUserId_ = getDefaultInstance().getOnlyUserId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string onlyUserId = 2;</code>
     * @param value The bytes for onlyUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOnlyUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      onlyUserId_ = value;
      onChanged();
      return this;
    }

    private com.xhpolaris.idlgen.basic.PaginationOptions paginationOption_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xhpolaris.idlgen.basic.PaginationOptions, com.xhpolaris.idlgen.basic.PaginationOptions.Builder, com.xhpolaris.idlgen.basic.PaginationOptionsOrBuilder> paginationOptionBuilder_;
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     * @return Whether the paginationOption field is set.
     */
    public boolean hasPaginationOption() {
      return paginationOptionBuilder_ != null || paginationOption_ != null;
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     * @return The paginationOption.
     */
    public com.xhpolaris.idlgen.basic.PaginationOptions getPaginationOption() {
      if (paginationOptionBuilder_ == null) {
        return paginationOption_ == null ? com.xhpolaris.idlgen.basic.PaginationOptions.getDefaultInstance() : paginationOption_;
      } else {
        return paginationOptionBuilder_.getMessage();
      }
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     */
    public Builder setPaginationOption(com.xhpolaris.idlgen.basic.PaginationOptions value) {
      if (paginationOptionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        paginationOption_ = value;
        onChanged();
      } else {
        paginationOptionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     */
    public Builder setPaginationOption(
        com.xhpolaris.idlgen.basic.PaginationOptions.Builder builderForValue) {
      if (paginationOptionBuilder_ == null) {
        paginationOption_ = builderForValue.build();
        onChanged();
      } else {
        paginationOptionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     */
    public Builder mergePaginationOption(com.xhpolaris.idlgen.basic.PaginationOptions value) {
      if (paginationOptionBuilder_ == null) {
        if (paginationOption_ != null) {
          paginationOption_ =
            com.xhpolaris.idlgen.basic.PaginationOptions.newBuilder(paginationOption_).mergeFrom(value).buildPartial();
        } else {
          paginationOption_ = value;
        }
        onChanged();
      } else {
        paginationOptionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     */
    public Builder clearPaginationOption() {
      if (paginationOptionBuilder_ == null) {
        paginationOption_ = null;
        onChanged();
      } else {
        paginationOption_ = null;
        paginationOptionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     */
    public com.xhpolaris.idlgen.basic.PaginationOptions.Builder getPaginationOptionBuilder() {
      
      onChanged();
      return getPaginationOptionFieldBuilder().getBuilder();
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     */
    public com.xhpolaris.idlgen.basic.PaginationOptionsOrBuilder getPaginationOptionOrBuilder() {
      if (paginationOptionBuilder_ != null) {
        return paginationOptionBuilder_.getMessageOrBuilder();
      } else {
        return paginationOption_ == null ?
            com.xhpolaris.idlgen.basic.PaginationOptions.getDefaultInstance() : paginationOption_;
      }
    }
    /**
     * <code>.basic.PaginationOptions paginationOption = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xhpolaris.idlgen.basic.PaginationOptions, com.xhpolaris.idlgen.basic.PaginationOptions.Builder, com.xhpolaris.idlgen.basic.PaginationOptionsOrBuilder> 
        getPaginationOptionFieldBuilder() {
      if (paginationOptionBuilder_ == null) {
        paginationOptionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xhpolaris.idlgen.basic.PaginationOptions, com.xhpolaris.idlgen.basic.PaginationOptions.Builder, com.xhpolaris.idlgen.basic.PaginationOptionsOrBuilder>(
                getPaginationOption(),
                getParentForChildren(),
                isClean());
        paginationOption_ = null;
      }
      return paginationOptionBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.core_api.GetPlanPreviewsReq)
  }

  // @@protoc_insertion_point(class_scope:meowchat.core_api.GetPlanPreviewsReq)
  private static final com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq();
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPlanPreviewsReq>
      PARSER = new com.google.protobuf.AbstractParser<GetPlanPreviewsReq>() {
    @java.lang.Override
    public GetPlanPreviewsReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetPlanPreviewsReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPlanPreviewsReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.GetPlanPreviewsReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

