// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/like.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public final class LikeProto {
  private LikeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_DoLikeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_DoLikeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_DoLikeResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_DoLikeResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetUserLikedReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetUserLikedReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetUserLikedResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetUserLikedResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetLikedCountReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetLikedCountReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetLikedCountResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetLikedCountResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetUserLikesReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetUserLikesReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetUserLikesResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetUserLikesResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetLikedUsersReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetLikedUsersReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetLikedUsersResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetLikedUsersResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034meowchat/core_api/like.proto\022\021meowchat" +
      ".core_api\032\032meowchat/user/common.proto\"J\n" +
      "\tDoLikeReq\022\020\n\010targetId\030\001 \001(\t\022+\n\ntargetTy" +
      "pe\030\002 \001(\0162\027.meowchat.user.LikeType\"\035\n\nDoL" +
      "ikeResp\022\017\n\007isFirst\030\001 \001(\010\"P\n\017GetUserLiked" +
      "Req\022\020\n\010targetId\030\001 \001(\t\022+\n\ntargetType\030\002 \001(" +
      "\0162\027.meowchat.user.LikeType\"!\n\020GetUserLik" +
      "edResp\022\r\n\005liked\030\001 \001(\010\"Q\n\020GetLikedCountRe" +
      "q\022\020\n\010targetId\030\001 \001(\t\022+\n\ntargetType\030\002 \001(\0162" +
      "\027.meowchat.user.LikeType\"\"\n\021GetLikedCoun" +
      "tResp\022\r\n\005count\030\001 \001(\003\"N\n\017GetUserLikesReq\022" +
      "\016\n\006userId\030\001 \001(\t\022+\n\ntargetType\030\002 \001(\0162\027.me" +
      "owchat.user.LikeType\"6\n\020GetUserLikesResp" +
      "\022\"\n\005likes\030\001 \003(\0132\023.meowchat.user.Like\"Q\n\020" +
      "GetLikedUsersReq\022\020\n\010targetId\030\001 \001(\t\022+\n\nta" +
      "rgetType\030\002 \001(\0162\027.meowchat.user.LikeType\"" +
      ">\n\021GetLikedUsersResp\022)\n\005users\030\001 \003(\0132\032.me" +
      "owchat.user.UserPreviewBG\n%com.xhpolaris" +
      ".idlgen.meowchat.coreapiB\tLikeProtoP\001Z\021m" +
      "eowchat/core_apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xhpolaris.idlgen.meowchat.user.CommonProto.getDescriptor(),
        });
    internal_static_meowchat_core_api_DoLikeReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meowchat_core_api_DoLikeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_DoLikeReq_descriptor,
        new java.lang.String[] { "TargetId", "TargetType", });
    internal_static_meowchat_core_api_DoLikeResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meowchat_core_api_DoLikeResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_DoLikeResp_descriptor,
        new java.lang.String[] { "IsFirst", });
    internal_static_meowchat_core_api_GetUserLikedReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meowchat_core_api_GetUserLikedReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetUserLikedReq_descriptor,
        new java.lang.String[] { "TargetId", "TargetType", });
    internal_static_meowchat_core_api_GetUserLikedResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_meowchat_core_api_GetUserLikedResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetUserLikedResp_descriptor,
        new java.lang.String[] { "Liked", });
    internal_static_meowchat_core_api_GetLikedCountReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_meowchat_core_api_GetLikedCountReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetLikedCountReq_descriptor,
        new java.lang.String[] { "TargetId", "TargetType", });
    internal_static_meowchat_core_api_GetLikedCountResp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_meowchat_core_api_GetLikedCountResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetLikedCountResp_descriptor,
        new java.lang.String[] { "Count", });
    internal_static_meowchat_core_api_GetUserLikesReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_meowchat_core_api_GetUserLikesReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetUserLikesReq_descriptor,
        new java.lang.String[] { "UserId", "TargetType", });
    internal_static_meowchat_core_api_GetUserLikesResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_meowchat_core_api_GetUserLikesResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetUserLikesResp_descriptor,
        new java.lang.String[] { "Likes", });
    internal_static_meowchat_core_api_GetLikedUsersReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_meowchat_core_api_GetLikedUsersReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetLikedUsersReq_descriptor,
        new java.lang.String[] { "TargetId", "TargetType", });
    internal_static_meowchat_core_api_GetLikedUsersResp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_meowchat_core_api_GetLikedUsersResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetLikedUsersResp_descriptor,
        new java.lang.String[] { "Users", });
    com.xhpolaris.idlgen.meowchat.user.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
