// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/system.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

/**
 * Protobuf type {@code meowchat.core_api.ListCommunityResp}
 */
public final class ListCommunityResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.core_api.ListCommunityResp)
    ListCommunityRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ListCommunityResp.newBuilder() to construct.
  private ListCommunityResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ListCommunityResp() {
    communities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ListCommunityResp();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_ListCommunityResp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_ListCommunityResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp.class, com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp.Builder.class);
  }

  public static final int COMMUNITIES_FIELD_NUMBER = 1;
  private java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Community> communities_;
  /**
   * <code>repeated .meowchat.core_api.Community communities = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Community> getCommunitiesList() {
    return communities_;
  }
  /**
   * <code>repeated .meowchat.core_api.Community communities = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.xhpolaris.idlgen.meowchat.coreapi.CommunityOrBuilder> 
      getCommunitiesOrBuilderList() {
    return communities_;
  }
  /**
   * <code>repeated .meowchat.core_api.Community communities = 1;</code>
   */
  @java.lang.Override
  public int getCommunitiesCount() {
    return communities_.size();
  }
  /**
   * <code>repeated .meowchat.core_api.Community communities = 1;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.Community getCommunities(int index) {
    return communities_.get(index);
  }
  /**
   * <code>repeated .meowchat.core_api.Community communities = 1;</code>
   */
  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.CommunityOrBuilder getCommunitiesOrBuilder(
      int index) {
    return communities_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < communities_.size(); i++) {
      output.writeMessage(1, communities_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < communities_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, communities_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp other = (com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp) obj;

    if (!getCommunitiesList()
        .equals(other.getCommunitiesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCommunitiesCount() > 0) {
      hash = (37 * hash) + COMMUNITIES_FIELD_NUMBER;
      hash = (53 * hash) + getCommunitiesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.core_api.ListCommunityResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.core_api.ListCommunityResp)
      com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_ListCommunityResp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_ListCommunityResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp.class, com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (communitiesBuilder_ == null) {
        communities_ = java.util.Collections.emptyList();
      } else {
        communities_ = null;
        communitiesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.SystemProto.internal_static_meowchat_core_api_ListCommunityResp_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp build() {
      com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp buildPartial() {
      com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp result = new com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp(this);
      int from_bitField0_ = bitField0_;
      if (communitiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          communities_ = java.util.Collections.unmodifiableList(communities_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.communities_ = communities_;
      } else {
        result.communities_ = communitiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp other) {
      if (other == com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp.getDefaultInstance()) return this;
      if (communitiesBuilder_ == null) {
        if (!other.communities_.isEmpty()) {
          if (communities_.isEmpty()) {
            communities_ = other.communities_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCommunitiesIsMutable();
            communities_.addAll(other.communities_);
          }
          onChanged();
        }
      } else {
        if (!other.communities_.isEmpty()) {
          if (communitiesBuilder_.isEmpty()) {
            communitiesBuilder_.dispose();
            communitiesBuilder_ = null;
            communities_ = other.communities_;
            bitField0_ = (bitField0_ & ~0x00000001);
            communitiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCommunitiesFieldBuilder() : null;
          } else {
            communitiesBuilder_.addAllMessages(other.communities_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.xhpolaris.idlgen.meowchat.coreapi.Community m =
                  input.readMessage(
                      com.xhpolaris.idlgen.meowchat.coreapi.Community.parser(),
                      extensionRegistry);
              if (communitiesBuilder_ == null) {
                ensureCommunitiesIsMutable();
                communities_.add(m);
              } else {
                communitiesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Community> communities_ =
      java.util.Collections.emptyList();
    private void ensureCommunitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        communities_ = new java.util.ArrayList<com.xhpolaris.idlgen.meowchat.coreapi.Community>(communities_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.coreapi.Community, com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder, com.xhpolaris.idlgen.meowchat.coreapi.CommunityOrBuilder> communitiesBuilder_;

    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Community> getCommunitiesList() {
      if (communitiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(communities_);
      } else {
        return communitiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public int getCommunitiesCount() {
      if (communitiesBuilder_ == null) {
        return communities_.size();
      } else {
        return communitiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Community getCommunities(int index) {
      if (communitiesBuilder_ == null) {
        return communities_.get(index);
      } else {
        return communitiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder setCommunities(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Community value) {
      if (communitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommunitiesIsMutable();
        communities_.set(index, value);
        onChanged();
      } else {
        communitiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder setCommunities(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder builderForValue) {
      if (communitiesBuilder_ == null) {
        ensureCommunitiesIsMutable();
        communities_.set(index, builderForValue.build());
        onChanged();
      } else {
        communitiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder addCommunities(com.xhpolaris.idlgen.meowchat.coreapi.Community value) {
      if (communitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommunitiesIsMutable();
        communities_.add(value);
        onChanged();
      } else {
        communitiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder addCommunities(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Community value) {
      if (communitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCommunitiesIsMutable();
        communities_.add(index, value);
        onChanged();
      } else {
        communitiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder addCommunities(
        com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder builderForValue) {
      if (communitiesBuilder_ == null) {
        ensureCommunitiesIsMutable();
        communities_.add(builderForValue.build());
        onChanged();
      } else {
        communitiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder addCommunities(
        int index, com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder builderForValue) {
      if (communitiesBuilder_ == null) {
        ensureCommunitiesIsMutable();
        communities_.add(index, builderForValue.build());
        onChanged();
      } else {
        communitiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder addAllCommunities(
        java.lang.Iterable<? extends com.xhpolaris.idlgen.meowchat.coreapi.Community> values) {
      if (communitiesBuilder_ == null) {
        ensureCommunitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, communities_);
        onChanged();
      } else {
        communitiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder clearCommunities() {
      if (communitiesBuilder_ == null) {
        communities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        communitiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public Builder removeCommunities(int index) {
      if (communitiesBuilder_ == null) {
        ensureCommunitiesIsMutable();
        communities_.remove(index);
        onChanged();
      } else {
        communitiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder getCommunitiesBuilder(
        int index) {
      return getCommunitiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.CommunityOrBuilder getCommunitiesOrBuilder(
        int index) {
      if (communitiesBuilder_ == null) {
        return communities_.get(index);  } else {
        return communitiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public java.util.List<? extends com.xhpolaris.idlgen.meowchat.coreapi.CommunityOrBuilder> 
         getCommunitiesOrBuilderList() {
      if (communitiesBuilder_ != null) {
        return communitiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(communities_);
      }
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder addCommunitiesBuilder() {
      return getCommunitiesFieldBuilder().addBuilder(
          com.xhpolaris.idlgen.meowchat.coreapi.Community.getDefaultInstance());
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder addCommunitiesBuilder(
        int index) {
      return getCommunitiesFieldBuilder().addBuilder(
          index, com.xhpolaris.idlgen.meowchat.coreapi.Community.getDefaultInstance());
    }
    /**
     * <code>repeated .meowchat.core_api.Community communities = 1;</code>
     */
    public java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder> 
         getCommunitiesBuilderList() {
      return getCommunitiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.xhpolaris.idlgen.meowchat.coreapi.Community, com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder, com.xhpolaris.idlgen.meowchat.coreapi.CommunityOrBuilder> 
        getCommunitiesFieldBuilder() {
      if (communitiesBuilder_ == null) {
        communitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.xhpolaris.idlgen.meowchat.coreapi.Community, com.xhpolaris.idlgen.meowchat.coreapi.Community.Builder, com.xhpolaris.idlgen.meowchat.coreapi.CommunityOrBuilder>(
                communities_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        communities_ = null;
      }
      return communitiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.core_api.ListCommunityResp)
  }

  // @@protoc_insertion_point(class_scope:meowchat.core_api.ListCommunityResp)
  private static final com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp();
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListCommunityResp>
      PARSER = new com.google.protobuf.AbstractParser<ListCommunityResp>() {
    @java.lang.Override
    public ListCommunityResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListCommunityResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListCommunityResp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.ListCommunityResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

