// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/collection.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface NewCatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.NewCatReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string age = 2;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <code>string age = 2;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();

  /**
   * <code>string communityId = 3;</code>
   * @return The communityId.
   */
  java.lang.String getCommunityId();
  /**
   * <code>string communityId = 3;</code>
   * @return The bytes for communityId.
   */
  com.google.protobuf.ByteString
      getCommunityIdBytes();

  /**
   * <code>string color = 4;</code>
   * @return The color.
   */
  java.lang.String getColor();
  /**
   * <code>string color = 4;</code>
   * @return The bytes for color.
   */
  com.google.protobuf.ByteString
      getColorBytes();

  /**
   * <code>string details = 5;</code>
   * @return The details.
   */
  java.lang.String getDetails();
  /**
   * <code>string details = 5;</code>
   * @return The bytes for details.
   */
  com.google.protobuf.ByteString
      getDetailsBytes();

  /**
   * <code>string name = 6;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 6;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string sex = 7;</code>
   * @return The sex.
   */
  java.lang.String getSex();
  /**
   * <code>string sex = 7;</code>
   * @return The bytes for sex.
   */
  com.google.protobuf.ByteString
      getSexBytes();

  /**
   * <code>string area = 8;</code>
   * @return The area.
   */
  java.lang.String getArea();
  /**
   * <code>string area = 8;</code>
   * @return The bytes for area.
   */
  com.google.protobuf.ByteString
      getAreaBytes();

  /**
   * <code>bool isSnipped = 9;</code>
   * @return The isSnipped.
   */
  boolean getIsSnipped();

  /**
   * <code>bool isSterilized = 10;</code>
   * @return The isSterilized.
   */
  boolean getIsSterilized();

  /**
   * <code>repeated string avatars = 11;</code>
   * @return A list containing the avatars.
   */
  java.util.List<java.lang.String>
      getAvatarsList();
  /**
   * <code>repeated string avatars = 11;</code>
   * @return The count of avatars.
   */
  int getAvatarsCount();
  /**
   * <code>repeated string avatars = 11;</code>
   * @param index The index of the element to return.
   * @return The avatars at the given index.
   */
  java.lang.String getAvatars(int index);
  /**
   * <code>repeated string avatars = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the avatars at the given index.
   */
  com.google.protobuf.ByteString
      getAvatarsBytes(int index);
}
