// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/moment.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface NewMomentRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.NewMomentResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string momentId = 1;</code>
   * @return The momentId.
   */
  java.lang.String getMomentId();
  /**
   * <code>string momentId = 1;</code>
   * @return The bytes for momentId.
   */
  com.google.protobuf.ByteString
      getMomentIdBytes();

  /**
   * <code>bool getFish = 2;</code>
   * @return The getFish.
   */
  boolean getGetFish();

  /**
   * <code>int64 getFishTimes = 3;</code>
   * @return The getFishTimes.
   */
  long getGetFishTimes();
}
