// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/post.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public final class PostProto {
  private PostProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_Post_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_Post_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_SearchOptions_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_SearchOptions_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetPostPreviewsReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetPostPreviewsReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetPostPreviewsResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetPostPreviewsResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetPostDetailReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetPostDetailReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_GetPostDetailResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_GetPostDetailResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_NewPostReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_NewPostReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_NewPostResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_NewPostResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_DeletePostReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_DeletePostReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_DeletePostResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_DeletePostResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_SetOfficialReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_SetOfficialReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_meowchat_core_api_SetOfficialResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_meowchat_core_api_SetOfficialResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034meowchat/core_api/post.proto\022\021meowchat" +
      ".core_api\032\026basic/pagination.proto\032\032meowc" +
      "hat/user/common.proto\"\322\001\n\004Post\022\n\n\002id\030\001 \001" +
      "(\t\022\020\n\010createAt\030\002 \001(\003\022\020\n\010updateAt\030\003 \001(\003\022\r" +
      "\n\005title\030\005 \001(\t\022\014\n\004text\030\006 \001(\t\022\020\n\010coverUrl\030" +
      "\007 \001(\t\022\014\n\004tags\030\010 \003(\t\022(\n\004user\030\t \001(\0132\032.meow" +
      "chat.user.UserPreview\022\022\n\nisOfficial\030\n \001(" +
      "\010\022\r\n\005likes\030\013 \001(\003\022\020\n\010comments\030\014 \001(\003\"}\n\rSe" +
      "archOptions\022\020\n\003key\030\001 \001(\tH\000\210\001\001\022\022\n\005title\030\002" +
      " \001(\tH\001\210\001\001\022\021\n\004text\030\003 \001(\tH\002\210\001\001\022\020\n\003tag\030\004 \001(" +
      "\tH\003\210\001\001B\006\n\004_keyB\010\n\006_titleB\007\n\005_textB\006\n\004_ta" +
      "g\"\354\001\n\022GetPostPreviewsReq\0222\n\020paginationOp" +
      "tion\030\001 \001(\0132\030.basic.PaginationOptions\022\031\n\014" +
      "onlyOfficial\030\002 \001(\010H\000\210\001\001\022\027\n\nonlyUserId\030\003 " +
      "\001(\tH\001\210\001\001\022<\n\rsearchOptions\030\004 \001(\0132 .meowch" +
      "at.core_api.SearchOptionsH\002\210\001\001B\017\n\r_onlyO" +
      "fficialB\r\n\013_onlyUserIdB\020\n\016_searchOptions" +
      "\"[\n\023GetPostPreviewsResp\022&\n\005posts\030\001 \003(\0132\027" +
      ".meowchat.core_api.Post\022\r\n\005total\030\002 \001(\003\022\r" +
      "\n\005token\030\003 \001(\t\"\"\n\020GetPostDetailReq\022\016\n\006pos" +
      "tId\030\001 \001(\t\":\n\021GetPostDetailResp\022%\n\004post\030\001" +
      " \001(\0132\027.meowchat.core_api.Post\"a\n\nNewPost" +
      "Req\022\017\n\002id\030\001 \001(\tH\000\210\001\001\022\r\n\005title\030\002 \001(\t\022\014\n\004t" +
      "ext\030\003 \001(\t\022\020\n\010coverUrl\030\004 \001(\t\022\014\n\004tags\030\005 \003(" +
      "\tB\005\n\003_id\"D\n\013NewPostResp\022\016\n\006postId\030\001 \001(\t\022" +
      "\017\n\007getFish\030\002 \001(\010\022\024\n\014getFishTimes\030\003 \001(\003\"\033" +
      "\n\rDeletePostReq\022\n\n\002id\030\001 \001(\t\"\020\n\016DeletePos" +
      "tResp\"D\n\016SetOfficialReq\022\016\n\006postId\030\001 \001(\t\022" +
      "\025\n\010isRemove\030\002 \001(\010H\000\210\001\001B\013\n\t_isRemove\"\021\n\017S" +
      "etOfficialRespBG\n%com.xhpolaris.idlgen.m" +
      "eowchat.coreapiB\tPostProtoP\001Z\021meowchat/c" +
      "ore_apib\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xhpolaris.idlgen.basic.PaginationProto.getDescriptor(),
          com.xhpolaris.idlgen.meowchat.user.CommonProto.getDescriptor(),
        });
    internal_static_meowchat_core_api_Post_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_meowchat_core_api_Post_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_Post_descriptor,
        new java.lang.String[] { "Id", "CreateAt", "UpdateAt", "Title", "Text", "CoverUrl", "Tags", "User", "IsOfficial", "Likes", "Comments", });
    internal_static_meowchat_core_api_SearchOptions_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_meowchat_core_api_SearchOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_SearchOptions_descriptor,
        new java.lang.String[] { "Key", "Title", "Text", "Tag", "Key", "Title", "Text", "Tag", });
    internal_static_meowchat_core_api_GetPostPreviewsReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_meowchat_core_api_GetPostPreviewsReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetPostPreviewsReq_descriptor,
        new java.lang.String[] { "PaginationOption", "OnlyOfficial", "OnlyUserId", "SearchOptions", "OnlyOfficial", "OnlyUserId", "SearchOptions", });
    internal_static_meowchat_core_api_GetPostPreviewsResp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_meowchat_core_api_GetPostPreviewsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetPostPreviewsResp_descriptor,
        new java.lang.String[] { "Posts", "Total", "Token", });
    internal_static_meowchat_core_api_GetPostDetailReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_meowchat_core_api_GetPostDetailReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetPostDetailReq_descriptor,
        new java.lang.String[] { "PostId", });
    internal_static_meowchat_core_api_GetPostDetailResp_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_meowchat_core_api_GetPostDetailResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_GetPostDetailResp_descriptor,
        new java.lang.String[] { "Post", });
    internal_static_meowchat_core_api_NewPostReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_meowchat_core_api_NewPostReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_NewPostReq_descriptor,
        new java.lang.String[] { "Id", "Title", "Text", "CoverUrl", "Tags", "Id", });
    internal_static_meowchat_core_api_NewPostResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_meowchat_core_api_NewPostResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_NewPostResp_descriptor,
        new java.lang.String[] { "PostId", "GetFish", "GetFishTimes", });
    internal_static_meowchat_core_api_DeletePostReq_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_meowchat_core_api_DeletePostReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_DeletePostReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_meowchat_core_api_DeletePostResp_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_meowchat_core_api_DeletePostResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_DeletePostResp_descriptor,
        new java.lang.String[] { });
    internal_static_meowchat_core_api_SetOfficialReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_meowchat_core_api_SetOfficialReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_SetOfficialReq_descriptor,
        new java.lang.String[] { "PostId", "IsRemove", "IsRemove", });
    internal_static_meowchat_core_api_SetOfficialResp_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_meowchat_core_api_SetOfficialResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_meowchat_core_api_SetOfficialResp_descriptor,
        new java.lang.String[] { });
    com.xhpolaris.idlgen.basic.PaginationProto.getDescriptor();
    com.xhpolaris.idlgen.meowchat.user.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
