// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/collection.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface SearchCatReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.SearchCatReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string keyword = 1;</code>
   * @return The keyword.
   */
  java.lang.String getKeyword();
  /**
   * <code>string keyword = 1;</code>
   * @return The bytes for keyword.
   */
  com.google.protobuf.ByteString
      getKeywordBytes();

  /**
   * <code>.basic.PaginationOptions paginationOption = 2;</code>
   * @return Whether the paginationOption field is set.
   */
  boolean hasPaginationOption();
  /**
   * <code>.basic.PaginationOptions paginationOption = 2;</code>
   * @return The paginationOption.
   */
  com.xhpolaris.idlgen.basic.PaginationOptions getPaginationOption();
  /**
   * <code>.basic.PaginationOptions paginationOption = 2;</code>
   */
  com.xhpolaris.idlgen.basic.PaginationOptionsOrBuilder getPaginationOptionOrBuilder();

  /**
   * <code>string communityId = 3;</code>
   * @return The communityId.
   */
  java.lang.String getCommunityId();
  /**
   * <code>string communityId = 3;</code>
   * @return The bytes for communityId.
   */
  com.google.protobuf.ByteString
      getCommunityIdBytes();
}
