// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/plan.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface SearchPlanRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.SearchPlanResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .meowchat.core_api.Plan plans = 1;</code>
   */
  java.util.List<com.xhpolaris.idlgen.meowchat.coreapi.Plan> 
      getPlansList();
  /**
   * <code>repeated .meowchat.core_api.Plan plans = 1;</code>
   */
  com.xhpolaris.idlgen.meowchat.coreapi.Plan getPlans(int index);
  /**
   * <code>repeated .meowchat.core_api.Plan plans = 1;</code>
   */
  int getPlansCount();
  /**
   * <code>repeated .meowchat.core_api.Plan plans = 1;</code>
   */
  java.util.List<? extends com.xhpolaris.idlgen.meowchat.coreapi.PlanOrBuilder> 
      getPlansOrBuilderList();
  /**
   * <code>repeated .meowchat.core_api.Plan plans = 1;</code>
   */
  com.xhpolaris.idlgen.meowchat.coreapi.PlanOrBuilder getPlansOrBuilder(
      int index);

  /**
   * <code>int64 total = 2;</code>
   * @return The total.
   */
  long getTotal();
}
