// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/auth.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

/**
 * Protobuf type {@code meowchat.core_api.SignInReq}
 */
public final class SignInReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:meowchat.core_api.SignInReq)
    SignInReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SignInReq.newBuilder() to construct.
  private SignInReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignInReq() {
    authType_ = "";
    authId_ = "";
    password_ = "";
    verifyCode_ = "";
    appId_ = 0;
    deviceId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SignInReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xhpolaris.idlgen.meowchat.coreapi.AuthProto.internal_static_meowchat_core_api_SignInReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xhpolaris.idlgen.meowchat.coreapi.AuthProto.internal_static_meowchat_core_api_SignInReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xhpolaris.idlgen.meowchat.coreapi.SignInReq.class, com.xhpolaris.idlgen.meowchat.coreapi.SignInReq.Builder.class);
  }

  private int bitField0_;
  public static final int AUTHTYPE_FIELD_NUMBER = 1;
  private volatile java.lang.Object authType_;
  /**
   * <code>string authType = 1;</code>
   * @return The authType.
   */
  @java.lang.Override
  public java.lang.String getAuthType() {
    java.lang.Object ref = authType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authType_ = s;
      return s;
    }
  }
  /**
   * <code>string authType = 1;</code>
   * @return The bytes for authType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthTypeBytes() {
    java.lang.Object ref = authType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHID_FIELD_NUMBER = 2;
  private volatile java.lang.Object authId_;
  /**
   * <pre>
   * authType为邮件时填邮箱，为电话时填电话号，为微信时填APP_ID
   * </pre>
   *
   * <code>string authId = 2;</code>
   * @return The authId.
   */
  @java.lang.Override
  public java.lang.String getAuthId() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * authType为邮件时填邮箱，为电话时填电话号，为微信时填APP_ID
   * </pre>
   *
   * <code>string authId = 2;</code>
   * @return The bytes for authId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthIdBytes() {
    java.lang.Object ref = authId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object password_;
  /**
   * <code>optional string password = 3;</code>
   * @return Whether the password field is set.
   */
  @java.lang.Override
  public boolean hasPassword() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string password = 3;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <code>optional string password = 3;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERIFYCODE_FIELD_NUMBER = 4;
  private volatile java.lang.Object verifyCode_;
  /**
   * <code>optional string verifyCode = 4;</code>
   * @return Whether the verifyCode field is set.
   */
  @java.lang.Override
  public boolean hasVerifyCode() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string verifyCode = 4;</code>
   * @return The verifyCode.
   */
  @java.lang.Override
  public java.lang.String getVerifyCode() {
    java.lang.Object ref = verifyCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verifyCode_ = s;
      return s;
    }
  }
  /**
   * <code>optional string verifyCode = 4;</code>
   * @return The bytes for verifyCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVerifyCodeBytes() {
    java.lang.Object ref = verifyCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verifyCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int APPID_FIELD_NUMBER = 5;
  private int appId_;
  /**
   * <code>.basic.APP appId = 5;</code>
   * @return The enum numeric value on the wire for appId.
   */
  @java.lang.Override public int getAppIdValue() {
    return appId_;
  }
  /**
   * <code>.basic.APP appId = 5;</code>
   * @return The appId.
   */
  @java.lang.Override public com.xhpolaris.idlgen.basic.APP getAppId() {
    @SuppressWarnings("deprecation")
    com.xhpolaris.idlgen.basic.APP result = com.xhpolaris.idlgen.basic.APP.valueOf(appId_);
    return result == null ? com.xhpolaris.idlgen.basic.APP.UNRECOGNIZED : result;
  }

  public static final int DEVICEID_FIELD_NUMBER = 6;
  private volatile java.lang.Object deviceId_;
  /**
   * <code>string deviceId = 6;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string deviceId = 6;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, authId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, verifyCode_);
    }
    if (appId_ != com.xhpolaris.idlgen.basic.APP.Unknown.getNumber()) {
      output.writeEnum(5, appId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, deviceId_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, authId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, verifyCode_);
    }
    if (appId_ != com.xhpolaris.idlgen.basic.APP.Unknown.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, appId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, deviceId_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xhpolaris.idlgen.meowchat.coreapi.SignInReq)) {
      return super.equals(obj);
    }
    com.xhpolaris.idlgen.meowchat.coreapi.SignInReq other = (com.xhpolaris.idlgen.meowchat.coreapi.SignInReq) obj;

    if (!getAuthType()
        .equals(other.getAuthType())) return false;
    if (!getAuthId()
        .equals(other.getAuthId())) return false;
    if (hasPassword() != other.hasPassword()) return false;
    if (hasPassword()) {
      if (!getPassword()
          .equals(other.getPassword())) return false;
    }
    if (hasVerifyCode() != other.hasVerifyCode()) return false;
    if (hasVerifyCode()) {
      if (!getVerifyCode()
          .equals(other.getVerifyCode())) return false;
    }
    if (appId_ != other.appId_) return false;
    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUTHTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getAuthType().hashCode();
    hash = (37 * hash) + AUTHID_FIELD_NUMBER;
    hash = (53 * hash) + getAuthId().hashCode();
    if (hasPassword()) {
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
    }
    if (hasVerifyCode()) {
      hash = (37 * hash) + VERIFYCODE_FIELD_NUMBER;
      hash = (53 * hash) + getVerifyCode().hashCode();
    }
    hash = (37 * hash) + APPID_FIELD_NUMBER;
    hash = (53 * hash) + appId_;
    hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xhpolaris.idlgen.meowchat.coreapi.SignInReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code meowchat.core_api.SignInReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:meowchat.core_api.SignInReq)
      com.xhpolaris.idlgen.meowchat.coreapi.SignInReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xhpolaris.idlgen.meowchat.coreapi.AuthProto.internal_static_meowchat_core_api_SignInReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xhpolaris.idlgen.meowchat.coreapi.AuthProto.internal_static_meowchat_core_api_SignInReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xhpolaris.idlgen.meowchat.coreapi.SignInReq.class, com.xhpolaris.idlgen.meowchat.coreapi.SignInReq.Builder.class);
    }

    // Construct using com.xhpolaris.idlgen.meowchat.coreapi.SignInReq.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      authType_ = "";

      authId_ = "";

      password_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      verifyCode_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      appId_ = 0;

      deviceId_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.AuthProto.internal_static_meowchat_core_api_SignInReq_descriptor;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.SignInReq getDefaultInstanceForType() {
      return com.xhpolaris.idlgen.meowchat.coreapi.SignInReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.SignInReq build() {
      com.xhpolaris.idlgen.meowchat.coreapi.SignInReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xhpolaris.idlgen.meowchat.coreapi.SignInReq buildPartial() {
      com.xhpolaris.idlgen.meowchat.coreapi.SignInReq result = new com.xhpolaris.idlgen.meowchat.coreapi.SignInReq(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.authType_ = authType_;
      result.authId_ = authId_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.password_ = password_;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        to_bitField0_ |= 0x00000002;
      }
      result.verifyCode_ = verifyCode_;
      result.appId_ = appId_;
      result.deviceId_ = deviceId_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xhpolaris.idlgen.meowchat.coreapi.SignInReq) {
        return mergeFrom((com.xhpolaris.idlgen.meowchat.coreapi.SignInReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xhpolaris.idlgen.meowchat.coreapi.SignInReq other) {
      if (other == com.xhpolaris.idlgen.meowchat.coreapi.SignInReq.getDefaultInstance()) return this;
      if (!other.getAuthType().isEmpty()) {
        authType_ = other.authType_;
        onChanged();
      }
      if (!other.getAuthId().isEmpty()) {
        authId_ = other.authId_;
        onChanged();
      }
      if (other.hasPassword()) {
        bitField0_ |= 0x00000001;
        password_ = other.password_;
        onChanged();
      }
      if (other.hasVerifyCode()) {
        bitField0_ |= 0x00000002;
        verifyCode_ = other.verifyCode_;
        onChanged();
      }
      if (other.appId_ != 0) {
        setAppIdValue(other.getAppIdValue());
      }
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              authType_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              authId_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              password_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 26
            case 34: {
              verifyCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 34
            case 40: {
              appId_ = input.readEnum();

              break;
            } // case 40
            case 50: {
              deviceId_ = input.readStringRequireUtf8();

              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object authType_ = "";
    /**
     * <code>string authType = 1;</code>
     * @return The authType.
     */
    public java.lang.String getAuthType() {
      java.lang.Object ref = authType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string authType = 1;</code>
     * @return The bytes for authType.
     */
    public com.google.protobuf.ByteString
        getAuthTypeBytes() {
      java.lang.Object ref = authType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string authType = 1;</code>
     * @param value The authType to set.
     * @return This builder for chaining.
     */
    public Builder setAuthType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string authType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthType() {
      
      authType_ = getDefaultInstance().getAuthType();
      onChanged();
      return this;
    }
    /**
     * <code>string authType = 1;</code>
     * @param value The bytes for authType to set.
     * @return This builder for chaining.
     */
    public Builder setAuthTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object authId_ = "";
    /**
     * <pre>
     * authType为邮件时填邮箱，为电话时填电话号，为微信时填APP_ID
     * </pre>
     *
     * <code>string authId = 2;</code>
     * @return The authId.
     */
    public java.lang.String getAuthId() {
      java.lang.Object ref = authId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * authType为邮件时填邮箱，为电话时填电话号，为微信时填APP_ID
     * </pre>
     *
     * <code>string authId = 2;</code>
     * @return The bytes for authId.
     */
    public com.google.protobuf.ByteString
        getAuthIdBytes() {
      java.lang.Object ref = authId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * authType为邮件时填邮箱，为电话时填电话号，为微信时填APP_ID
     * </pre>
     *
     * <code>string authId = 2;</code>
     * @param value The authId to set.
     * @return This builder for chaining.
     */
    public Builder setAuthId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      authId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * authType为邮件时填邮箱，为电话时填电话号，为微信时填APP_ID
     * </pre>
     *
     * <code>string authId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthId() {
      
      authId_ = getDefaultInstance().getAuthId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * authType为邮件时填邮箱，为电话时填电话号，为微信时填APP_ID
     * </pre>
     *
     * <code>string authId = 2;</code>
     * @param value The bytes for authId to set.
     * @return This builder for chaining.
     */
    public Builder setAuthIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      authId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <code>optional string password = 3;</code>
     * @return Whether the password field is set.
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string password = 3;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string password = 3;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      bitField0_ = (bitField0_ & ~0x00000001);
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <code>optional string password = 3;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000001;
      password_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object verifyCode_ = "";
    /**
     * <code>optional string verifyCode = 4;</code>
     * @return Whether the verifyCode field is set.
     */
    public boolean hasVerifyCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string verifyCode = 4;</code>
     * @return The verifyCode.
     */
    public java.lang.String getVerifyCode() {
      java.lang.Object ref = verifyCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verifyCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string verifyCode = 4;</code>
     * @return The bytes for verifyCode.
     */
    public com.google.protobuf.ByteString
        getVerifyCodeBytes() {
      java.lang.Object ref = verifyCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verifyCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string verifyCode = 4;</code>
     * @param value The verifyCode to set.
     * @return This builder for chaining.
     */
    public Builder setVerifyCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      verifyCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string verifyCode = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearVerifyCode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      verifyCode_ = getDefaultInstance().getVerifyCode();
      onChanged();
      return this;
    }
    /**
     * <code>optional string verifyCode = 4;</code>
     * @param value The bytes for verifyCode to set.
     * @return This builder for chaining.
     */
    public Builder setVerifyCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000002;
      verifyCode_ = value;
      onChanged();
      return this;
    }

    private int appId_ = 0;
    /**
     * <code>.basic.APP appId = 5;</code>
     * @return The enum numeric value on the wire for appId.
     */
    @java.lang.Override public int getAppIdValue() {
      return appId_;
    }
    /**
     * <code>.basic.APP appId = 5;</code>
     * @param value The enum numeric value on the wire for appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppIdValue(int value) {
      
      appId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.basic.APP appId = 5;</code>
     * @return The appId.
     */
    @java.lang.Override
    public com.xhpolaris.idlgen.basic.APP getAppId() {
      @SuppressWarnings("deprecation")
      com.xhpolaris.idlgen.basic.APP result = com.xhpolaris.idlgen.basic.APP.valueOf(appId_);
      return result == null ? com.xhpolaris.idlgen.basic.APP.UNRECOGNIZED : result;
    }
    /**
     * <code>.basic.APP appId = 5;</code>
     * @param value The appId to set.
     * @return This builder for chaining.
     */
    public Builder setAppId(com.xhpolaris.idlgen.basic.APP value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      appId_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.basic.APP appId = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAppId() {
      
      appId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string deviceId = 6;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deviceId = 6;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deviceId = 6;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      
      deviceId_ = getDefaultInstance().getDeviceId();
      onChanged();
      return this;
    }
    /**
     * <code>string deviceId = 6;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceId_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:meowchat.core_api.SignInReq)
  }

  // @@protoc_insertion_point(class_scope:meowchat.core_api.SignInReq)
  private static final com.xhpolaris.idlgen.meowchat.coreapi.SignInReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xhpolaris.idlgen.meowchat.coreapi.SignInReq();
  }

  public static com.xhpolaris.idlgen.meowchat.coreapi.SignInReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SignInReq>
      PARSER = new com.google.protobuf.AbstractParser<SignInReq>() {
    @java.lang.Override
    public SignInReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SignInReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignInReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xhpolaris.idlgen.meowchat.coreapi.SignInReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

