// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/core_api/system.proto

package com.xhpolaris.idlgen.meowchat.coreapi;

public interface UpdateSuperAdminRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.core_api.UpdateSuperAdminResp)
    com.google.protobuf.MessageOrBuilder {
}
