// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/sts/sts.proto

package com.xhpolaris.idlgen.platform.sts;

public interface SendVerifyCodeReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.sts.SendVerifyCodeReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string authType = 1;</code>
   * @return The authType.
   */
  java.lang.String getAuthType();
  /**
   * <code>string authType = 1;</code>
   * @return The bytes for authType.
   */
  com.google.protobuf.ByteString
      getAuthTypeBytes();

  /**
   * <pre>
   * 邮箱号或手机号
   * </pre>
   *
   * <code>string authId = 2;</code>
   * @return The authId.
   */
  java.lang.String getAuthId();
  /**
   * <pre>
   * 邮箱号或手机号
   * </pre>
   *
   * <code>string authId = 2;</code>
   * @return The bytes for authId.
   */
  com.google.protobuf.ByteString
      getAuthIdBytes();
}
