// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/sts/sts.proto

package com.xhpolaris.idlgen.platform.sts;

public interface SignInRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:platform.sts.SignInResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string openId = 2;</code>
   * @return The openId.
   */
  java.lang.String getOpenId();
  /**
   * <code>string openId = 2;</code>
   * @return The bytes for openId.
   */
  com.google.protobuf.ByteString
      getOpenIdBytes();

  /**
   * <code>string unionId = 3;</code>
   * @return The unionId.
   */
  java.lang.String getUnionId();
  /**
   * <code>string unionId = 3;</code>
   * @return The bytes for unionId.
   */
  com.google.protobuf.ByteString
      getUnionIdBytes();

  /**
   * <code>string appId = 4;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string appId = 4;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>bool isFirst = 5;</code>
   * @return The isFirst.
   */
  boolean getIsFirst();
}
