// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/user/user.proto

package com.xhpolaris.idlgen.meowchat.user;

public interface GetTargetLikesRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.user.GetTargetLikesResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 count = 1;</code>
   * @return The count.
   */
  long getCount();
}
