// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: meowchat/user/user.proto

package com.xhpolaris.idlgen.meowchat.user;

public interface GetUserLikesReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:meowchat.user.GetUserLikesReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.meowchat.user.LikeType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.meowchat.user.LikeType type = 2;</code>
   * @return The type.
   */
  com.xhpolaris.idlgen.meowchat.user.LikeType getType();
}
